### ISSUE TITLE
Popover utils is not accessible from index.ts

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI-react#103]
#### Actual behavior
You cannot import Popover Utils from iTwinUI-React without the full path.
#### Expected behavior
I would expect being able to import Popover component from normal import of iTwinUI-react and not ask to know the full path to import it.

#### Additional information
Also there is no doc on how to use it, so that make me wondering if this is design to be use by user of itwin-react or I should import my own popover lib of my choice?

**Comment by mayank99** [comment]
Yeah, this is intentional. `Popover` is an internal wrapper over **tippy.js** and not meant to be used directly.

You could use any popover lib but tippy.js is recommended because it will have the same API and not add any additional dependency.
