### ISSUE TITLE
FileUploadTemplate: Expose "accept" input attribute 

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI-react#122]
#### Feature
`FileUploadTemplate` exposes `multiple` attribute through `acceptMultiple`, adding the `accept` attribute of file would be helpful to guide the user. (Although it is not supported in IE, Chrome and Firefox supports it)

#### Examples
Could probably be a pass through (however it might be confusing with the `acceptMultiple` already there:
`<FileUploadTemplate accept='.dgn' acceptMultiple={false} />`

or

`<FileUploadTemplate acceptType='.dgn,.rvt' acceptMultiple={false} />`

**Comment by mayank99** [comment]
Available in 1.9.0 🎉
