### ISSUE TITLE
Table: Highlighting data to complement search features

### ISSUE THREAD

**Issue by MichaelBelousov** [iTwin/iTwinUI-react#126]
#### Feature
Add the ability in tables to specify a "highlighted subsection" string/regex, which can complement searches that filter the table rows, by drawing user attention to the part of the filtered columns that matches on their search.

This is especially useful when it runs as you type.
When a user only remembers keywords from a row they are search for, getting visual feedback of what projects match their keyword help them remember additional keywords they can use to narrow down their search query quickly. 

#### Examples
[https://review.itwin.bentley.com]([https://review.itwin.bentley.com) already does this:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/16315257/121377305-3a515300-c910-11eb-9e57-14b28a7f0b76.png)

You can see in their use case, they are passing a case-ignoring regex, so the `Ke` matches rows that have a lowercase `k`, and those are also highlighted.

**Comment by MichaelBelousov** [comment]
I plan on (eventually) submitting a PR for this myself

**Comment by mayank99** [comment]
Maybe we'll see this in 2022 👀 https://www.w3.org/TR/css-highlight-api-1/

**Comment by mayank99** [comment]
Looks like the CSS Highlight API is available in Chrome/Safari now, so this can be implemented in userland. Here's a demo: https://microsoftedge.github.io/Demos/custom-highlight-api/
