### ISSUE TITLE
Table filter triggers onSelect

### ISSUE THREAD

**Issue by klopez213** [iTwin/iTwinUI-react#141]
#### Environment
- __Package version(s)__: 1.8.0
- __Operating System__: Windows
- __Browser name and version__: Chrome 91.0.4472.101

#### Code Sandbox
Link to a minimal repro: https://codesandbox.io/s/table-filter-triggers-onselect-zjwk5

#### Steps to reproduce
1. Filter any of the columns.

#### Actual behavior
onSelect is triggered when filtering.  Please see Code Sandbox sample.

#### Expected behavior
onSelect shouldn't be triggered when filtering.

**Comment by mayank99** [comment]
Fixed in 1.8.1 🎉
