### ISSUE TITLE
Tooltip cannot force placement top / tooltip transparency hard to read when text under

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI-react#142]
#### Environment
- __Package version(s)__: 1.6.0
itwin-css: 0.17.1

#### Steps to reproduce
```tsx
<Tooltip
  content={message}
  placement="top"
>
  <span style={{ display: "flex" }}>
	<SvgStatusError />
  </span>
</Tooltip>
```
I try to replicate the setup I have, but I get a different result where tooltip is cut in half instead of going under.
https://codesandbox.io/s/itwinui-react-example-forked-5uih5?file=/src/App.tsx 

#### Actual behavior
So I'm doing an info panel, I have my tooltip placement to top but the tooltip appear under whatever I set the placement or not. Probably because there is no place at the top, but because the tooltip is transparent, I am not able to read the text of the tooltip. The text under make it confusing to read the tooltip. 
![image](https://user-images.githubusercontent.com/4070713/122302667-6c465480-ced0-11eb-8d46-9ffb2ee50c53.png)

#### Expected behavior
Placement="top" would force tooltip to appear at top. Or maybe [overflowContainer](https://github.com/everweij/react-laag#uselayeroptions) props ? Or fixing transparency in tooltip ?

**Comment by bentleyvk** [comment]
Hi, thanks for reaching us. As Mayank mentioned previously in your other feature request https://github.com/iTwin/iTwinUI-react/issues/137#issuecomment-861710570, we are planning to work on input statuses.
For now you can fix this by setting `appendTo={document.body}` in `Tooltip`.
Also, I hope those CSS overrides in your codesanbox is accidental and you are not having them in your product 🙂
![image](https://user-images.githubusercontent.com/36186912/122358272-2a172480-cf5d-11eb-81d2-55e4b4b39f71.png)

**Comment by mayank99** [comment]
Yeah, you should not need to set any css overrides in our components. See https://codesandbox.io/s/itwinui-react-example-forked-bg6pt?file=/src/App.tsx

First thing, I recommend updating to itwinui-react 1.8.0 so you can use the `size` prop in `LabeledInput`.

Secondly, I recommend looking at [tippy.js documentation](https://atomiks.github.io/tippyjs/) because our tooltip is a wrapper around that. By default, the tooltip is appended to the parent container, so it doesn't always have space. The documentation says:
> _If a tippy cannot fit within its desired placement, it will flip to the opposite placement._

Normally, this would all work out-of-the-box, but because of the way our elements are currently structured, the z-index stacking context can make the tooltip cut off if it needs to appear over an element that appears later in the DOM tree. Using `appendTo` will fix that, as it gives it a different stacking context.

---

As for the transparency/readability, that is something we can fix. Do you mind creating a new issue for that in the iTwinUI css repo? Thanks.

**Comment by maxime4000** [comment]
I think the issues here is the lack of example/documentation on the tooltip component : https://itwin.github.io/iTwinUI-react/?path=/docs/core-tooltip--top 
`appendTo` was what I need, so thanks for that !

From my point of view, which is someone who work with iTwinUI-React, but is not actively working with the source code. I don't really know what the tooltip is using behind. I have minimal knowledge about it, but not everyone has that. I suggest doing 2 things :
- Adding docs for the imported props from tippy.js
- Linking the docs of Tippy.js in your actual docs so if there is missing information in iTwinUI-React docs, you can go on tippy.js docs and find what's missing.

When I have issues with iTwinUI-React, I often look at the docs and when I don't find a fix, open the source code and try understanding what is missing or what could cause the problems. After I come here to write an issue.
In this case, all I need was someone that could point me to the right docs. So I guess more docs would have avoid me this visit.

**Comment by mayank99** [comment]
We do link to tippy.js docs in `Popover`. Maybe we should add it to the `Tooltip` JSDoc comment as well.

We thought this would be the expected "flow" a user would go through:
![tooltip](https://user-images.githubusercontent.com/9084735/122426993-b83fda80-cf5e-11eb-8c4a-f7ec0ea3af3a.gif)


Oh also, we've now added an FAQ section (which we will link in the README soon). https://github.com/iTwin/iTwinUI-react/wiki/FAQ

**Comment by maxime4000** [comment]
But wasn't the Popover a private component ? No storybook docs, nor available from `/index | /core/index`. 

By the way, navigating in iTwinUI-React from a solution that use it is not really helpful comparing navigating in the source code. From my workflow : I prefer if I don't have to open the solution of iTwinUI-React to understand what x-y props do. Using only JSDoc and storybook is what I would prefer. **Suggestion : Having storybook url link for the component in JSDoc ?**

Something that would also help is making props not importing all the HTML Element optional props. The list is too long and render the JSDoc useless as component props get mix in all the HTMLElement Props. Seeing this list hide the real usefulness of looking at props definition : 
![Find which props are LabeledInput vs which are Input Props ?](https://user-images.githubusercontent.com/4070713/122447898-35c11600-cf72-11eb-826f-48408a172d53.png)
 
I already talk about it before, but allowing those props to work even if they are not define would help understanding the definition of the current component you are trying to use. 
```.tsx
/** 
 * {...} 
 * @extends Can use all the props of React.ButtonHTMLAttributes<HTMLButtonElement> 
 */
export type ButtonProps = {
  // ...
  /** This will allow ButtonProps to have any other props. */
  [inheritsProps: string]: unknown;
}; // & React.ButtonHTMLAttributes<HTMLButtonElement>; Remove this part as this cause intellisense to be unhelpful.
```
