### ISSUE TITLE
Typeahead/searchable select

### ISSUE THREAD

**Issue by ChrisBAtBentley** [iTwin/iTwinUI-react#146]
Bentley's BWC library currently features a Typeahead (searchable select) component. However, this does not currently exist in iTwinUI. In order to make moving over to IUI from BWC smoother, it would be nice to have this component.

**Comment by mayank99** [comment]
Hi @ChrisBAtBentley 👋

BWC's Typeahead was based on [react-select](https://react-select.com/), which has tons of features (grouping, multi-select, asynchronous/lazy-loading, animations). We are trying to narrow down the scope of this component, so could you tell us what features are most important to you? I imagine you mainly need the "searchable select" (i.e. searching within a predefined list) part.

**Comment by ChrisBAtBentley** [comment]
At this time I believe we just need a way to search the select options.

**Comment by NitaKokat** [comment]
@mayank99 I am also looking for searchable select component. The reason is hundreds/thousands options are available for few users and it is difficult to scroll it and find for specific option. so this searchable select would be nice option for this.
