### ISSUE TITLE
Toast: 'warning' category

### ISSUE THREAD

**Issue by DanEastBentley** [iTwin/iTwinUI-react#148]
The Toast notification is missing a Warning status and hollow icon. The Alert has warning, and the iModel.js Toast/Sticky has warning. Please add the Warning status & hollow icon to the Toast notification.

**Comment by mayank99** [comment]
Moving this issue to react because css is now available for warning category.

As for the icon, we've decided to change all hollow variants to filled ones.

**Comment by mayank99** [comment]
Available in 1.9.0 🎉
