### ISSUE TITLE
Table: columns first level Header is not respected.

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI-react#153]
In order to get headers to be displayed in the table, we must actually create a root group (which is never displayed)
It is a bit unexpected behavior.

#### Environment
- __Package version(s)__: 1.7.2
- __Operating System__: Windows 10
- __Browser name and version__: Chrome, 91.0.4472.114

#### Code Sandbox
Link to a minimal repro: https://codesandbox.io/s/shy-wind-1sp5q?file=/src/App.js
This pits react-table example against itwinUi table, click on the Toggle Header Level to add/remove the grouping, the same data is fed to their example and iui table, notice that, the groupings are off.

#### Steps to reproduce
Please see the repo, compare the columns definition between grouped and not grouped and the behavior.

#### Actual behavior
In the sandbox, I get either "Ungrouped" headers, or no headers.

#### Expected behavior
In the sandbox, I expect a grouping level, and an "Ungrouped" header.

#### Additional information
There is a `.splice(1)` in the Table header code that seems to cause this issue, not sure why it is there.

**Comment by mayank99** [comment]
There are two parts to this issue:
1. First level `Header` is required, i.e. not including it removes the header completely. In other words, users have to add a dummy `Header` property even if they don't want grouped headers.
2. First level `Header` is ignored, i.e. Including it does not create a header group. To create a header group, users need to add the dummy header, and then specify their groups one level deeper.

@adamhock Can you clarify what part you're working on and how your PR tackles the breaking change? We need to make sure both bugs (ungrouped and grouped) are fixed, tested, and documented properly.

**Comment by adamhock** [comment]
> There are two parts to this issue:
> 
> 1. First level `Header` is required, i.e. not including it removes the header completely. In other words, users have to add a dummy `Header` property even if they don't want grouped headers.
> 2. First level `Header` is ignored, i.e. Including it does not create a header group. To create a header group, users need to add the dummy header, and then specify their groups one level deeper.
> 
> @adamhock Can you clarify what part you're working on and how your PR tackles the breaking change? We need to make sure both bugs (ungrouped and grouped) are fixed, tested, and documented properly.

#935 tackles both of these issues. First level `Header` is no longer required for `Table` components. If a first level `Header` is specified, it is no longer ignored. Instead, a table `Header` is placed above the column headers like so.

![image](https://user-images.githubusercontent.com/78564221/201698358-4135cda6-9954-407c-a610-9af2c5e4df21.png)

However, there is no support for header groups at this time. A new issue has been opened for that feature here: #938
