### ISSUE TITLE
Table: Single Select or onClick event handler for rows

### ISSUE THREAD

**Issue by lumiio** [iTwin/iTwinUI-react#155]
#### Feature
A single select table or an onClick handler for rows.

It may be technically possible to implement a single select table using onSelect (I am still in the process of figuring it out), but it's very hacky.

#### Examples
I am currently working on a demo showcase where on selecting/clicking a row, it will zoom into that particular part of an iModel. I would need an event handler for clicking on rows to do this. A single select table would be ok but not ideal in this situation, but either would work for my use case. There is a key value that is stored within the row clicked that is used to zoom in on the element within the viewer, so at the very least I need the data from the clicked row.

**Comment by mayank99** [comment]
I think this is closely related to allowing selection by clicking on rows.

From UX Standards:
![image](https://user-images.githubusercontent.com/9084735/122829742-62986480-d2b5-11eb-92ae-9de20c433d36.png)

As for the "single select" part, that can be done through `stateReducer`. See https://codesandbox.io/s/itwinui-react-minimal-example-forked-fy40u

But for your scenario, using a select table does seem hacky. The "right" approach (from a UX standpoint) might just be to have an _Action_ column, where you have a button or link.

**Comment by mayank99** [comment]
This is now available in 1.11.0 🎉

Clicking on a row will now select it and fire the `onRowClick` callback. `Ctrl` key can be used to select multiple rows.

Demo: https://itwin.github.io/iTwinUI-react/?path=/story/core-table--selectable
