### ISSUE TITLE
HorizontalTabs: requesting support for sublabel, icon, disabled & item keyboard navigation

### ISSUE THREAD

**Issue by DanEastBentley** [iTwin/iTwinUI-react#173]
Requesting new features for tabs in HorizontalTabs component in iTwinUI-react:
•	sublabel
•	icon
•	disabled state
•	item keyboard navigation for accessibility

The current iModel.js implementation looks like the following:

![TabFeatures](https://user-images.githubusercontent.com/51122937/119046826-26f33d80-b98b-11eb-8c14-73bf37e0b5c6.JPG)

**Comment by mayank99** [comment]
CSS is now available in 0.22.0. Moving this issue to react.

**Comment by mayank99** [comment]
Now available in iTwinUI-react 1.12.0 🎉
