### ISSUE TITLE
Table: expandable `subRows`

### ISSUE THREAD

**Issue by FelixGirard** [iTwin/iTwinUI-react#192]
#### Feature
A full integration of subRows. Like what they have in [React Table](https://react-table.tanstack.com/docs/examples/sub-components-lazy).

For our need, only one child depth is required.
It should work with selection and with sorting.

Please note that in our case, the parent and child have different selection.
For example, if I select the parent it shouldn't toggle the selection on all child.
We also think it would be nice to have an icon in the header to toggle the expansion of all rows.

#### Examples
Here is [a sandbox](https://codesandbox.io/s/itwinui-react-example-forked-84l4t?file=/src/App.tsx:1381-1382) by @mayank99 illustrating a partial implementation.

**Comment by veekeys** [comment]
Hey @FelixGirard 
Thank you for the request!
Could you give some more details about this part:
"Please note that in our case, the parent and child have different selection."
If you select all and it selects the first level row, it should not select the subrows of that row? That sounds really weird. If you have a valid use case for that, I do not think we will support that natively. That would go on your side to implement and control the selection state.

**Comment by FelixGirard** [comment]
Hi! 
Thanks for your response!

Here is our user workflow: 

1.  Select row or multiple rows where you want to modify some information.
2.  Make some changes.
3. The changes are applied to all selected rows.

The problem we have with our use case and the selection is that we want to be able to change the information on the parent independently from it's child.
In our case we could consider it grouping instead of hierarchy. (is that understandable?)

I would have liked it to be an option when using row selection but I could see why it would not be supported natively.

**Comment by mayank99** [comment]
@FelixGirard Thanks for creating the issue.

> I would have liked it to be an option when using row selection but I could see why it would not be supported natively.

This part is already supported in react-table. You can just pass `selectSubRows={false}` to `Table` and it should work out-of-the-box (try it in the sandbox 😄).

As for the rest of the issue, we will try to do it in a way that has sensible defaults (from a UX standpoint) but can't promise additional things like a "expand all rows" button. There is always a tradeoff between supporting extra use cases and adhering to UX standards (which is really the primary purpose of our library).

**Comment by mayank99** [comment]
This is now available and built into iTwinUI-react in v1.16.0 🎉

See story: https://itwin.github.io/iTwinUI-react/?path=/story/core-table--expandable-subrows

Note that when some rows do not have sub-rows, it is recommended to pass empty array to `subRows` for consistent spacing.
