### ISSUE TITLE
Can use tab key to focus out of modal

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI-react#195]
I can use the tab key to send the focus outside of the modal.  See the focus is on the side navigation in this screenshot.
![Screen Shot 2021-07-08 at 5 24 47 PM](https://user-images.githubusercontent.com/849817/124992857-8677dc00-e011-11eb-9516-7d9511f3b794.png)

**Comment by mayank99** [comment]
This can be pretty complicated to do, even in 2021.

Examples:
https://micromodal.vercel.app/
https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/dialog-modal/js/dialog.js

The good news is, we will soon get an [`inert`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert) attribute which makes it really easy. It's currently only available behind a flag. https://caniuse.com/mdn-api_htmlelement_inert

**Comment by bentleyvk** [comment]
I thought I have created an issue/card for this but must have left in Azure backlog. It is called "focus trap" but we need to do it manually.
