### ISSUE TITLE
Overflow button group

### ISSUE THREAD

**Issue by mis046** [iTwin/iTwinUI-react#196]
#### Feature
If the toolbar grows beyond it’s available horizontal or vertical space, we place the tools within an overflow button. When the overflow button is selected, an additional toolbar slides perpendicular away from the overflow button.

#### Examples
![image](https://user-images.githubusercontent.com/9084735/125132024-b7b7e100-e0d1-11eb-8fc7-e6227e120ac3.png)

**Comment by mayank99** [comment]
Hi @mis046 👋 Thanks for the issue!

It seems there are two parts to your feature request:
1. Overflow (hiding extra buttons)
2. Vertical button group

The first part is relatively simple, especially if you know how many icons you need to show. But if it needs to be responsive based on available width, then it's a bit more involved but still achievable. See https://codesandbox.io/s/itwinui-react-minimal-example-forked-r0ror

For the second part, I would suggest creating a feature request in the [iTwinUI-css repo](https://github.com/iTwin/iTwinUI/issues), as we will need to add the styles there before we can offer a vertical react component.

**Comment by mayank99** [comment]
@FlyersPh9 These two parts combined are an App UI feature. How much of this do we want to support in iTwinUI?

**Comment by FlyersPh9** [comment]
The ability to overflow a button group should be added to iTwinUI.  But the overflow menu would open a regular menu with icon + label combo.
![Screen Shot 2021-07-12 at 5 12 57 PM](https://user-images.githubusercontent.com/849817/125356681-8854de80-e334-11eb-9c7e-b37fb8349011.png)

**Comment by mis046** [comment]
@FlyersPh9 It is good as long as we have the overflow feature for the button group. The look of the overflow menu doesn't matter that much. We've implemented our own overflow feature for now (thanks for the example @mayank99), but it would be better if it is built in the button group. Please keep us updated on the native overflow feature. Thanks!

**Comment by mayank99** [comment]
This is now available in v1.16.0 🎉

See story: https://itwin.github.io/iTwinUI-react/?path=/story/buttons-buttongroup--overflow
