### ISSUE TITLE
Table: header and rows don't overflow properly when columns have minWidth

### ISSUE THREAD

**Issue by basanta078** [iTwin/iTwinUI-react#199]
#### Environment
- __Package version(s)__: 1.6
- __Operating System__: windows
- __Browser name and version__: Chrome Version 91.0.4472.124

#### Code Sandbox
Link to a minimal repro: https://codesandbox.io/s/itwinui-react-example-forked-7tkx7

#### Steps to reproduce
1. Click "ClickMe" button
2.  It opens a table with columns that have set minimum width
3. scroll horizontally to see data on the right

#### Actual behavior
columns hidden are not displayed correctly
check box column is also not displayed correctly

#### Expected behavior
When scrolled horizontally columns should be rendered properly
Checkbox column should be rendered properly

#### Additional information
![image](https://user-images.githubusercontent.com/2604235/125515494-fea098a8-fd17-448e-b66b-95d7232e6131.png)

**Comment by mayank99** [comment]
Fix is now available in iTwinUI-react 1.12.0 🎉
