### ISSUE TITLE
Table: Add onMouseEnter/onMouseLeave for rows

### ISSUE THREAD

**Issue by S-Bra** [iTwin/iTwinUI-react#216]
#### Feature
Please report onMouseEnter and onMouseLeave for rows and let implementers pass callbacks for it to the table component. 

Add to TableProps<T>
```
onMouseEnter?: (event: React.MouseEvent, row: Row<T>) => void 
onMouseLeave?:  (event: React.MouseEvent, row: Row<T>) => void 

```
#### Examples
Highlight elements in a graphical view when hovering the associated data in the table.

**Comment by mayank99** [comment]
This is now available in 1.14.0 🚀

You can pass `onMouseEnter`/`onMouseLeave` handlers in the new `rowProps` prop.
