### ISSUE TITLE
Footer component : we can't override default elements 

### ISSUE THREAD

**Issue by anandgaikwad** [iTwin/iTwinUI-react#223]
#### Describe the bug (actual behavior)

Currently we can't show custom footer only, it will always shows default footer with custom elements.

#### Expected behavior

As our components are public, there should a way to override default footer.

#### Reproduction
Link to a minimal repro: 

##### Steps to reproduce
1.  Try to show only custom footer elements.

**Comment by bentleyvk** [comment]
If I understand you correctly, you want to show only your custom items inside the footer, right?
Correct me if I am wrong but all the links in the `Footer` are required by our legal department.

**Comment by veekeys** [comment]
We might have products outside of Bentley org, so they might need different links than to Bentley.
This is a good idea.
@anandgaikwad just to confirm, is there a need for you project to have non Bentley links for some reason? So we could prioritize accordingly.
