### ISSUE TITLE
Smaller Tables - Reduce Table Row Height

### ISSUE THREAD

**Issue by monikapw** [iTwin/iTwinUI-react#224]
#### Feature
We want to use smaller tables to best fit the content. It is possible if there is any way we could reduce the row height. If you see here currently there is a lot of spacing between the rows. We want to utilize the empty space on the page for other components
![image](https://user-images.githubusercontent.com/29201321/127314368-8549a649-c16f-457c-a8c6-6dede3303372.png)

**Comment by mayank99** [comment]
This is now available in iTwinUI-react 1.15.0 🚀 Use the `density` prop.
https://itwin.github.io/iTwinUI-react/?path=/story/core-table--condensed
