### ISSUE TITLE
Add Id props to SelectOption<T> 

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI-react#225]
#### Feature
When writing e2e test, you want to have direct access to element you want to do some actions on it. That mean having some way to click on a specifics item in the select dropdown. I suggest adding Id as optional props in SelectOption<T>.

**Comment by mayank99** [comment]
Do you really need an id just for testing? Playwright even [recommends](https://playwright.dev/docs/selectors/#:~:text=to%20reduce%20the%20maintenance%20burden%2C%20we%20recommend%20prioritizing%20user-facing%20attributes%20and%20explicit%20contracts.) testing with user-facing attributes first.
```ts
await page.$('text="Select option 2"')
```

**Comment by maxime4000** [comment]
It's not because it's recommends that is the only way to get things done. My worries here are that the string can be shown more than once and I can get the wrong element and the test will fail to do what it's suppose to do. Translation can get in the way too, so I don't see anything wrong with ID if it's for improving reliability.

**Comment by bentleyvk** [comment]
I think it is really bad to show select which has items with the same names.

**Comment by maxime4000** [comment]
I think it's not your place to judge how people use the lib. You don't know what is the context, where I use it and I don't need to explain the full situation to justify if adding an optional ID props in the SelectOption type is a good idea or not.

**Comment by veekeys** [comment]
@maxime4000, we do not judge anything here. We are trying to figure out the use case first, before dropping everything to add whatever is needed.
Also, we are trying to help people with the UI/UX of the products, so they could be better.
Can you explain the situation, how you can have same text option elements under a single Select?
You can have selector in playwright to select a specific Select (use id for it) and then choose option by text keeping that Select context. Link which was provided above by @mayank99 has a demo of it.

**Comment by maxime4000** [comment]
I never said it's in the same select, all I'm saying is that id is more reliable than text for selector. In our case is not about making sure a user is finding the right option, it's about simulating interaction with our elements, applying some changes, submit those changes and expecting the same outcome now and two years from now if we don't change this feature. ID won't change, translation might. (Probably not in this case, but that's not the point here)

**Comment by mayank99** [comment]
This is now available in 1.16.0 🎉
