### ISSUE TITLE
Slider Thumb is not retaining its focus when value changed via keyboard

### ISSUE THREAD

**Issue by bsteinbk** [iTwin/iTwinUI-react#233]
Slider Thumb is not retaining its focus when value changed via keyboard.

#### Expected behavior
A thumb is focused user should be able to adjust value by pressing arrow key multiple times.

#### Reproduction
```
export const ProcessChange: Story<Partial<SliderProps>> = (args) => {
  const [sliderValues, setSliderValues] = React.useState([20, 40]);

  return (
    <Slider
      {...args}
      values={sliderValues}
      onChange={(values) => setSliderValues([...values])}
    />
  );
};

ProcessChange.args = {
  min: 0,
  max: 60,
  tickLabels: ['0', '20', '40', '60'],
  tooltipProps: (index, val) => {
    return { placement: 'right', content: `\$${val}.00` };
  },
};
```

##### Steps to reproduce
1. Use above code 
1. Set focus to first thumb
1. Press Arrow key and note that after the first key press focus is lost

#### Additional information
See proposed fix  in  https://github.com/iTwin/iTwinUI-react/pull/232

**Comment by mayank99** [comment]
This is now available in 1.14.0 🎉
