### ISSUE TITLE
ExpandableBlock: Jumping screen on Select placed under content

### ISSUE THREAD

**Issue by irenajur** [iTwin/iTwinUI-react#243]
#### Describe the bug (actual behavior)
Select component placed under Expandable block makes dropdown behavior strange: screen is jumping to Select dropdown no matter what was the initial scroll position. If you are at the top of page it will jump down to dropdown, at the bottom of page - will jump up to dropdown. Also Select dropdown is always positioned under Select field, while w/o Expandable block it might be placed above if there is not enough space under the field.

#### Expected behavior
Select placed under Expandable block should behave the same as w/o using Expandable block. 
Like in this example: [Example w/o Expandable block usage - CodeSandbox](https://codesandbox.io/s/itwinui-react-example-forked-urt53?file=/src/App.tsx)

#### Reproduction
Link to a minimal repro: [Example with Expandable block usage - CodeSandbox](https://codesandbox.io/s/itwinui-react-example-forked-xfjkj?file=/src/App.tsx)

##### Steps to reproduce
1. Expand block
1. Click on Select component

**Result:** Screen jumps down to dropdown area while w/o Expandable block dropdown content is displayed above the select.

1. Expand block
1. Scroll down to the end of example
1. Click on Select component

**Result:** Screen jumps up to dropdown area even if it's enough place to show dropdown w/o jumping.

**Comment by bentleyvk** [comment]
Hi Irena, tank you for reporting this bug. It seems that the problem is caused by `transform: scaleY(...)` that we are using to animate the expansion. As a workaround you can apply custom class to `ExpandableBlock`:
```css
.my-expandable-block .iui-expandable-content {
  transform: unset !important;
}
```

**Comment by mayank99** [comment]
The animation has been updated in 1.16.0 and the bug should be fixed 🎉
