### ISSUE TITLE
Pressing Arrow Keys when Slider Thumb has focus propagates to container scrollbars

### ISSUE THREAD

**Issue by bsteinbk** [iTwin/iTwinUI-react#247]
Pressing Arrow Keys when Slider Thumb has focus propagates to container scrollbars

#### Describe the bug (actual behavior)
Pressing Arrow Keys when Slider Thumb has focus propagates to container scrollbars

#### Expected behavior
If key is processed by slider it should not propagate to any other control.

#### Reproduction
https://codesandbox.io/s/itwinui-react-minimal-example-forked-fczxg 

##### Steps to reproduce
1. Open sandbox
1. Select Thumb to focus it
1. Press arrow, home or end keys

**Comment by mayank99** [comment]
Fix is now available in 1.14.1
