### ISSUE TITLE
Add "Split Button" type of Header Button

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI-react#253]
#### Feature
Current header buttons are either dropdown buttons (click on the full button and get the dropdown) or simple buttons (click on the button and do something.)

In the header, we would need the "main" part of the button to do something (For example, bring me to the currently "active" project and do something with it) and the drop down part to select a different project and do likely the same thing.

Current connect implementation does this but is rather tricky to click only on the carret image, which does a different thing than the rest of the button.

Not 100% sure of how it should look, but the split button might be a starting point, where the 2 different click targets  highlights separately, I dont know if the current | in the middle of the component would do well

### Basic

![image](https://user-images.githubusercontent.com/1904889/120532652-e5608a80-c3ad-11eb-9b38-68dc830ae423.png)

### Main hover

![image](https://user-images.githubusercontent.com/1904889/120532619-d7ab0500-c3ad-11eb-990d-bd83f0f6c2c9.png)

### Drop down

![image](https://user-images.githubusercontent.com/1904889/120532503-b9dda000-c3ad-11eb-9557-b406db427995.png)

(Examples made by pasting header button code in split button "left" button, so styling is not great)

**Comment by mayank99** [comment]
CSS is now available in 0.25.0. Moving this issue to React.

**Comment by mayank99** [comment]
This is now available in iTwinUI-react 1.15.0 🚀 Pass both `onClick` and `menuItems` to make the `HeaderButton` split.
