### ISSUE TITLE
Size of the modal is very small.

### ISSUE THREAD

**Issue by jawariawaseem1** [iTwin/iTwinUI-react#259]
#### Describe the bug (actual behavior)
Size of the modal in the itwinui is very small as compare to the one in bwc-react library.
![image](https://user-images.githubusercontent.com/88484680/129176713-3881a606-ad22-4d2c-b0a3-5e9ba255a812.png)

#### Expected behavior
It should be of this size. (This one is from bwc-react)
![image](https://user-images.githubusercontent.com/88484680/129176563-db8d4796-f796-4820-a4f1-ac24c7ca3beb.png)

Or there should be a mechanism to change its styling as currently I have to override the CSS styling of the core component elements to make it look better.

**Comment by bentleyvk** [comment]
This is our new modal look. Maybe @FlyersPh9 can comment on that.
If you really really don't like new modal, all our components has `classname` and `style` props that let you override stylings.

**Comment by mayank99** [comment]
> I have to override the CSS styling of the core component elements to make it look better.

I think that's perfectly fine, unless you need to use `!important` or you are doing some complex overrides that require the knowledge of internal classnames.

**Comment by jawariawaseem1** [comment]
` unless you need to use !important or you are doing some complex overrides that require the knowledge of internal classnames.`
That's exactly what I am doing. For eg if I need to increase the size of the title, I had to do this

.iui-modal > .iui-modal-dialog .iui-title-bar > .iui-title {
  font-size: 24px;
}

which requires the knowledge of internal classnames.

**Comment by FlyersPh9** [comment]
Hey @jawariawaseem1, most components in iTwinUI are a little more condensed than they were in BWC.  iTwinUI is used within AppUI which requires more dense components, so the modal is displaying as expected.

I would suggest adding `margin-top: round($iui-baseline / 2);` & `margin-bottom: round($iui-baseline / 2);` to your "Select file" component to give it a little more breathing room, but everything else looks good.
![Screen Shot 2021-08-17 at 10 37 45 AM](https://user-images.githubusercontent.com/849817/129746379-dc1c302c-98c6-4b63-8808-8a1545252aa8.png)

**Comment by veekeys** [comment]
Hey @jawariawaseem1. As @FlyersPh9 mentioned, this is the new standard for the Modal component. Font sizes in there are a part of it and should not be overridden. Whole modal is more compact and having less white space, so user can concentrate on the content in there. You can still apply your own styling to the container of the modal (change inner padding), if there is a huge need for it.
I am closing this issue. Feel free to reopen or create a new one, if you find some issues with it.

P.S. do not use the old modal you have in your screenshot... Title is really badly aligned with the close icon in there :(
