### ISSUE TITLE
HeaderButton pass menuItems prop to underlying button resulting in React warning

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI-react#269]
#### Describe the bug (actual behavior)
When using `HeaderButton` component, if I pass an `undefined` `menuItems` prop, react is complaining that it does not recognise `menuItems` as valid for the `button`:
![image](https://user-images.githubusercontent.com/1904889/129964211-cc20657b-a2f3-4683-aa70-1aa437116c5b.png)

#### Expected behavior
No warning is expected when I provide a prop with an `undefined` value to an optional prop, while I dont have statistics, I think this is a common use of optional props.

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/itwinui-react-example-forked-s1y94?file=/src/App.tsx

##### Steps to reproduce
In the repro above, 
Open the console drawer, notice that it is empty.

Click on the first "Toggle menu items" link, notice that the error shown above will display.

Reload the page to "reset" the errors. (Otherwise, it will not display more error, but that doesnt mean anything 😄, it would not show a second error even if we have 2 of the same behavior )

Click on the second "Toggle menu items" link, notice that no error shows up. 

#### Additional information
The second method I used to do the optional prop actually destructure an object, which contains or not the `menuItems` property.
This way, when the underlying component applies the `...rest` to the `button` component, the `menuItems` prop does not exist and it does not complain. (Howerver, I dont think this is a common way of applying conditional props to a component)

**Comment by mayank99** [comment]
I don't see anything in the sandbox. Did you forget to save?

**Comment by raplemie** [comment]
Apparently. Should be good now, maybe.

**Comment by mayank99** [comment]
At first it did not make sense to me why React is complaining, but apparently it's "expected behavior" and the component should strip undefined props before passing it to React. https://github.com/facebook/react/issues/7266

**Comment by mayank99** [comment]
Fixed in 1.16.0 🚀
