### ISSUE TITLE
Error page: image size changes on text change

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI-react#27]
Error page image size must be static, now it depends on error text width

**Comment by mayank99** [comment]
This is an easy. Basically we are using the wrong class in react (should be "illustration" not "icon") https://github.com/iTwin/iTwinUI-react/blob/58aa4fa04236da6d1830fc8ba7b4386f47bf9935/src/core/ErrorPage/ErrorPage.tsx#L114

I believe @FlyersPh9 was working on class renames for non ideal state, so we could wait for that.
