### ISSUE TITLE
Toast: height is explicitly set

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI-react#28]
_From @maxime4000:_

> This is uncommon because to get this display you need to edit the content of the toast, but why is height set in the first place ? Not needed.
> ![image](https://user-images.githubusercontent.com/9084735/116747459-f0e61d80-a9cb-11eb-8dc4-4fae71496925.png)
>

**Comment by mayank99** [comment]
@maxime4000 I don't understand the issue here. What problem is the explicit height causing? Can you provide more details as to what's expected vs observed behavior?

**Comment by maxime4000** [comment]
What I'm saying is that height of toast are calculate when they show up, but unless there is a edge case that force this settings, there is no need to pre calculate the height of toast.

**Comment by mayank99** [comment]
Well, those inline styles are needed for making the animations work. See comparison below.

Without:
![without](https://user-images.githubusercontent.com/9084735/116934904-8fc08300-ac33-11eb-823b-bfe6eaf95409.gif)

Current behavior (with):
![with](https://user-images.githubusercontent.com/9084735/116934906-90f1b000-ac33-11eb-91bd-b0eb4994f3c9.gif)

I'm closing this issue. Feel free to reopen if you're noticing an actual bug.
