### ISSUE TITLE
Investigate react-transition-group for animating table subrows

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI-react#298]

**Comment by maxime4000** [comment]
I'm using the lib in our project. Would recommend.

**Comment by veekeys** [comment]
> I'm using the lib in our project. Would recommend.

Yeah, we are using it too. But it did not work out in subrows... I got it working for that, but it messes up lazy load then (our subrows is just another row in the dom), and I could not find proper way to have conditional css transition. Feel free to play around and submit PR, if you make it work.

**Comment by mayank99** [comment]
Closing this as, we are not going to do this. We can reopen if that changes.
