### ISSUE TITLE
Tooltip component should be a forwardRef component

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI-react#299]
#### Describe the bug (actual behavior)
Tooltips isn't a forwardRef component and cannot be add in a DropdownMenu. If added, tooltip work, but no dropdown. 
```
<DropdownMenu menuItems={items}>
  <Tooltip content={"text"}>
    <IconButton>
      <SvgSomething/>
    </IconButton>
  </Tooltip>
</DropdownMenu>
```
`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

Can work with this workflow but unnecessary div wrapper is needed : 
```
<DropdownMenu menuItems={items}>
  <div>
    <Tooltip content={"text"}>
      <IconButton>
        <SvgSomething/>
      </IconButton>
    </Tooltip>
  </div>
</DropdownMenu>
```

#### Expected behavior
No wrapper div is necessary in this case. Seem like Tooltip was design to allow ref as props. Maybe this package could help : react-merge-refs ?

#### Suggestion : 
Having some props of tooltip in Button component ?

**Comment by mayank99** [comment]
@maxime4000 We tried to forward ref in #300 but it doesn't fix your DropdownMenu+Tooltip use case.

Maybe you can use `reference` prop if you don't like the extra wrapper div.
![image](https://user-images.githubusercontent.com/9084735/131517111-23db83f2-4dde-48a4-9dba-96bb9c7f2f63.png)
