### ISSUE TITLE
Disabled button: tooltip is not shown

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI-react#30]
> Add a Button component.
> Wrap Button in Tooltip component.
> Open browser - tooltip appears as expected.
> Add disabled prop to Button.
> Open browser - tooltip no longer appears.

**Comment by mayank99** [comment]
I think we can close this because it's expected behavior and has a workaround.

From https://github.com/atomiks/tippyjs-react/issues/123#issuecomment-535148835
> _If you're setting disabled, use a wrapper `<span>`_

**Comment by Juliakas** [comment]
Wrapping it in span works well, tooltip is shown on disabled buttons. There's an issue with ButtonGroup component styling - it seems that there are lots of first of type, last of type, sibling and other selectors that use button as basis. Wrapping button in span would mean that span should be the basis for selector relationships and it would still need to apply styles to buttons themselves, not span element. Is it even possible with pure css?

**Comment by veekeys** [comment]
@Juliakas This is going to be complicated.. I dont think we could provide such selectors.. Also, leaving broad selector (apply to all level child button) would brake some other cases... If we cant find a nice workaround, we might need to handle this specific case somehow at our end then..
@mayank99 @FlyersPh9 lets not forget this issue on our next backlog planning.

**Comment by mayank99** [comment]
> There's an issue with ButtonGroup component styling

This is now fixed in iTwinUI-css v1.28.0
