### ISSUE TITLE
Tooltip overflowing outside of the viewport.

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI-react#313]
#### Describe the bug (actual behavior)
I have a tooltip at the right of my page and when the tooltip is showing, the text is crop by the limit of the window.
![image](https://user-images.githubusercontent.com/4070713/132574071-8f71cca4-a815-44a0-abc3-ab932247e3f5.png)

#### Expected behavior
Tooltip bubble would be less wide and use more the height or the arrow wouldn't be center but place to the right of the bubble. 

![TooltipPlacementExample](https://user-images.githubusercontent.com/4070713/132573783-4b675ad3-c979-4513-b7ee-5e3d537e32f1.gif)

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/itwinui-react-example-forked-bhjst

**Comment by veekeys** [comment]
Fixed in 1.18.0 🚀
