### ISSUE TITLE
Ability to have Button as anchor

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI-react#332]
In certain Link cases, there might be a need to have our Button displayed as anchor (accessbility) when it is navigatin to some page. Need to think if it makes sense to provide `as` prop and render button as anchor..

**Comment by mayank99** [comment]
Is it about rendering button as anchor or anchor as button? The title and description are saying kinda opposite things.

- For button as anchor: I think we might need some CSS changes too, to make sure every state looks ok. I already noticed that hover state is broken if I render `<a class='iui-button'>`.
- For anchor as button: We don't really have a Link/anchor component, so it would need more than just a prop. Unless we add an anchor variant to our `Text` component.
