### ISSUE TITLE
RadioTileGroup: missing status

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI-react#342]
Need to support same as InputGroup

**Comment by veekeys** [comment]
Also, add `CommonProps` to `RadioTileGroup`

**Comment by mayank99** [comment]
`CommonProps` makes sense, but what would `status` even look like? It doesn't do anything by itself.

![image](https://user-images.githubusercontent.com/9084735/135885548-252cde8f-8a78-4f1e-980f-4ae9f650b149.png)
![image](https://user-images.githubusercontent.com/9084735/135885521-a21911be-9be5-4a03-b67e-ab217350f53d.png)

Or do you also need `message` and `icon` to be supported?

**Comment by veekeys** [comment]
@mayank99 Could you check ways to have a tooltip over RadioTile...?
