### ISSUE TITLE
Modal close button is out of place

### ISSUE THREAD

**Issue by jawariawaseem1** [iTwin/iTwinUI-react#343]
#### Describe the bug (actual behavior)
The close button (cross icon) is getting way too far from the right side of the modal.
![image](https://user-images.githubusercontent.com/88484680/135392252-820d9463-36f1-455f-a4de-6deb307f0b3c.png)

#### Expected behavior
The close button should be close to the right side of the modal like this
![image](https://user-images.githubusercontent.com/88484680/135393303-f13bf5a2-39e1-46ef-8ba8-b9672477edb1.png)

#### Possible fix
Removing this width possibly resolves this issue.
![image](https://user-images.githubusercontent.com/88484680/135393073-60458725-3d76-44ee-8d8c-86d6a4876618.png)

**Comment by bentleyvk** [comment]
Hi, could you make a minimal repro from this sandbox: https://codesandbox.io/s/itwinui-react-example-son74?
Because I don't see this CSS in our [demo page](https://itwin.github.io/iTwinUI-react/?path=/story/core-modal--basic). It seems that you might have some overrides that has the same selector.

**Comment by jawariawaseem1** [comment]
There was another package that was causing this issue, I'm closing this issue.
