### ISSUE TITLE
Button: notification marker

### ISSUE THREAD

**Issue by bentleyvk** [iTwin/iTwinUI-react#348]
Add notification marker to the button as we have CSS for it https://github.com/iTwin/iTwinUI/pull/293
![image](https://user-images.githubusercontent.com/849817/133502630-e65997a8-0129-4acd-b3ac-acc9284bea42.gif)

**Comment by mayank99** [comment]
Not sure if this would go in `Button`. It is actually applied on the icon within the button.

**Comment by bentleyvk** [comment]
But if applied to the icon, users will have to manually add a class or use some kind of a wrapper that we should provide. I was thinking of having a prop whether to show marker or not but it would require additional props for status color and whether it is urgent.
Hm, maybe it is really better to have some wrapper that would just clone the icon and add required classes.

**Comment by mayank99** [comment]
@bentleyvk This is now released in v2.2.0 and you can use it in your app 😄
