### ISSUE TITLE
add window control options to header for frameless-window electron applications

### ISSUE THREAD

**Issue by MichaelBelousov** [iTwin/iTwinUI-react#367]
#### Feature

add items to the right of the `userIcon` spot in the `Header` component,
particularly for window controls in frameless-window electron applications that use their header as the frame.

Example:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/16315257/136790289-93a69162-2caa-47c0-ae13-832bce79c919.png)

So the header would need some new prop like `windowControls`, similar in type to the children prop which get placed in the center currently.

It may also be of important to make sure that the header has good drag-ability in this mode. See the documentation here:
https://www.electronjs.org/docs/api/frameless-window#draggable-region
I have tested adding the following style to my header which seemed to do the trick:

```scss
.myHeaderClass {
  -webkit-app-region: drag;
  > * {
    -webkit-app-region: none;
  }
}
```

**Comment by MichaelBelousov** [comment]
I'll try that out, can a note be added about that for other people that try to use the `userIcon` prop but want it moved?

**Comment by mayank99** [comment]
`userIcon` has been deprecated in [v2](https://github.com/iTwin/iTwinUI-react/releases/tag/v2.0.0)
