### ISSUE TITLE
Menu: When `MenuItem` has actionable elements, arrow navigation is going trough them

### ISSUE THREAD

**Issue by bentleyvk** [iTwin/iTwinUI-react#379]
When `MenuExtraContent` has actionable elements, arrow navigation is going trough them.
Need to only allow arrow navigation through menu items.

**Comment by veekeys** [comment]
There is one more issue, if menu item has anchor, navigation is messed up, cause it goes twice on same menu item.

**Comment by mayank99** [comment]
I have renamed the issue as it applies to all menu items. If the item has a checkbox in it, then arrow key navigation goes through it (#564)
