### ISSUE TITLE
Slider: `onChange` called multiple times during arrow key navigation and `onUpdate` never called

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI-react#398]
_From https://github.com/iTwin/iTwinUI-react/pull/346#issuecomment-949826671:_

> `onChangeCompleted` is called dozens of times when dragging the dot using arrow keys (instead of only being called on keyup). This happens in both the color square **and the slider**, and it makes the dragging feel laggy especially when combined with a console log.

This behavior should only apply to `onUpdate`, which is instead never called when using keyboard to change values. Contrast to using a mouse, where `onChange` is only called on pointerUp and `onUpdate` is called during dragging.

### Repro

Use arrow left/right keys and observe console in the sandbox. https://codesandbox.io/s/itwinui-react-minimal-example-forked-1q46q?file=/src/App.tsx

**Comment by muthubentley** [comment]
Refer to below sandbox to reproduce the behavior:
https://www.itwinjs.org/sandbox/MuthuKalamani/SliderWithKeyboardIssue
-Mouse click on slider --> alert message will be shown with the slider value
-Move the slider knob --> alert message will be shown with the slider value
-press right and left buttons in Keyboard --> alert message will not be shown
