### ISSUE TITLE
DatePicker: onChange should not have date argument as optional

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI-react#426]
![image](https://user-images.githubusercontent.com/81580355/141284669-5d65dfe3-43d2-42fd-89b9-04761108a8bd.png)

This does not really make sense as on change will always return date. Also, it makes usage of date picker not nice as you need to save variable with `Date | undefined` type.
Just this change might be done only on v2 as it looks like a breaking one..

**Comment by mayank99** [comment]
How is it a breaking change?  You can make it not optional and it should not change usage.

You would still be able to do this:
```tsx
onChange={() => {}}
```

Here's an example from `Select` (the `value` arg is not optional):
![image](https://user-images.githubusercontent.com/9084735/141306557-55d3edea-d0bf-4943-9b96-0fc28e880ed0.png)
https://github.com/iTwin/iTwinUI-react/blob/b863b1d8917be9b64954bce03d75f60eb5f80d7a/src/core/Select/Select.tsx#L69

**Comment by veekeys** [comment]
Simply.

![image](https://user-images.githubusercontent.com/81580355/141307759-bd66fa2f-a0fe-4e7f-8523-ef872880a439.png)

![image](https://user-images.githubusercontent.com/81580355/141307787-12676b5a-4733-4402-923f-9d0b142db0dd.png)

**Comment by mayank99** [comment]
That would still not be a breaking change. If the users are already setting type of their state as `Date | undefined`, then narrowing down the type would still be valid.

**Comment by veekeys** [comment]
So breaking the build after library update now is not considered as breaking change?

**Comment by veekeys** [comment]
Ok, might be not a breaking change after all... We can make this fix.
