### ISSUE TITLE
Table: expandable rows

### ISSUE THREAD

**Issue by Juliakas** [iTwin/iTwinUI-react#43]
#### Feature
We would like to utilize react-table's expander features: https://react-table.tanstack.com/docs/examples/expanding.

Currently we have bwc tables supporting that and would like to migrate to iTwinUI variant (see examples).

##### Table with expander, single nesting
![image](https://user-images.githubusercontent.com/36437897/116856090-2a549e00-ac03-11eb-97bb-a55f22bfd76a.png)

##### Table with expander, infinite nesting
![image](https://user-images.githubusercontent.com/36437897/116856263-81f30980-ac03-11eb-8e4c-a34c08f1915d.png)

**Comment by Juliakas** [comment]
#50

**Comment by mayank99** [comment]
This is now available in 1.10.0 🎉
