### ISSUE TITLE
TablePaginator: ellipsis is shown at wrong time

### ISSUE THREAD

**Issue by bentleyvk** [iTwin/iTwinUI-react#432]
Ellipsis shouldn't be shown when centre part has '2' at the beginning, ellipsis shouldn't be shown.
![image](https://user-images.githubusercontent.com/36186912/141809620-ab41ba79-6f8d-49ad-8fa6-b2ceb77229ae.png)

**Comment by mayank99** [comment]
Can you add repro steps/link?

It looks fine on my end
![image](https://user-images.githubusercontent.com/9084735/141810438-65fa3704-0a6d-4c83-8104-181155940616.png)

**Comment by mayank99** [comment]
But you fixed that in the next push 😆
