### ISSUE TITLE
Table: EditableCell should expose an `onValueChange` prop

### ISSUE THREAD

**Issue by ChrisBAtBentley** [iTwin/iTwinUI-react#443]
We have an input that keeps track of its own state so that the user can make edits to data displayed in a table. However, even though the input keeps track of its own state, whenever focus is lost on an input that has been edited, a double click is needed to focus on another control in the table. Users also cannot use keystrokes to move between inputs if there are multiple in the table. This occurs even when using useMemo or useCallback in the table and did not occur in previous Bentley UI packages.

An example can be seen here: https://codesandbox.io/s/itwinui-react-minimal-example-forked-gvrof?file=/src/App.tsx. Click one text input, then attempt to click another. Notice that it takes two clicks to focus the next one.

**Comment by mayank99** [comment]
Thanks for the issue.

> This occurs even when using useMemo or useCallback in the table and did not occur in previous Bentley UI packages.

You are not memoizing your `columns` and your state updater is dependent on the state itself, so it is causing a rerender on every blur event.

You can fix this by using a function in your setState to get the old value. https://reactjs.org/docs/hooks-reference.html#functional-updates

```diff
- columns={[
+ columns={React.useMemo(
+  () => [
    {
      id: "fix",
      columns: [
        {
          Header: "Label",
          accessor: "display"
        },
        {
          Header: "Data",
-          Cell: ({ row }: any) => (
-            <StateInput
-              initialValue={row.original.data}
-              onFinished={(item: string) => {
-                let allNew = [...testData];
-                allNew[row.index].data = item;
-                setTestData(allNew);
-              }}
-            />
-          )
+          Cell: (cell: Cell<TableTest>) => (
+            <StateInput
+              initialValue={cell.row.original.data}
+              onFinished={(value: string) => {
+                setTestData((old) =>
+                  old.map((row, index) => {
+                    if (index === cell.row.index) {
+                      return { ...old[cell.row.index], data: value };
+                    }
+                    return row;
+                  })
+                );
+              }}
+            />
+          )
        }
      ]
    }
- ]}
+  ],
+  []
+)}
```

Also consider using our in-built `EditableCell` instead. https://itwin.github.io/iTwinUI-react/?path=/story/core-table--editable

Closing this. Please feel free to comment if you still think there is an issue.

**Comment by ChrisBAtBentley** [comment]
I've tried the suggestions listed here, but we are running into a few issues; some grids need to be reloaded due to new calculations after an input is given which memoization prevents, and some inputs need code run on them on onInput (similar to EditableCell's sanitizing), which EditableCell doesn't support. Is there a solution for either of these?

**Comment by bentleyvk** [comment]
Can you give full repo with all the things you want to achieve? That way we would know what to suggest you or make a fix on our side.

**Comment by bentleyvk** [comment]
So if I understand you correctly, you now only need `onValChange` like prop in `EditableCell` so you could do validations on user input, right?

**Comment by ChrisBAtBentley** [comment]
That's correct. The original issue still occurs in text inputs that aren't EditableCell, but the additional functionality of onValChange would make EditableCell an equivalent control for us in our product.

**Comment by mayank99** [comment]
> and some inputs need code run on them on onInput to edit the state
> the additional functionality of onValChange would make EditableCell an equivalent control for us in our product

I'm not fully understanding the problem here. EditableCell gives you the ability to run your own `onInput` after its own, and it also exposes the final value in `onCellEdit`. Does that not satisfy your needs?

**Comment by ChrisBAtBentley** [comment]
No; while we can run an onInput, it does not give the ability to alter the cell's state. We need a way to add to the EditableCell's current onInput that will edit its internal state after each input. See the sandbox for an example of the functionality we're looking for.

**Comment by mayank99** [comment]
I am lost here, so you will need to clarify a bit more and we will try our best to help.

1. The issue title is "Making edits to a control in a Table needs a double click to refocus". I am not seeing this problem anymore after you added memoization and state updater functions.

2. You keep pointing to the updated codesandbox but it seems to be working perfectly for me, so I am again not seeing the problem. Could you clearly describe what's the issue in the current sandbox?

3. You are also asking about the ability to change the "internal state" in EditableCell. But it's a `contenteditable` div so its state is managed automatically. The sanitization of the displayed value actually happens just by ignoring the Enter key in `onKeyDown`. You can pass your own `onKeyDown` to ignore additional keys. The only purpose of the internal `value` is to pass it back via `onCellEdit` so you do have the ability to modify it before updating table state. Can you try all this and create a new sandbox if there is another problem with it?

**Comment by bentleyvk** [comment]
It is very inconvenient using `onKeyDown`, `onPaste`, also I think there is more events that you need to handle, I don't remember now. And it seems like `onValueChange` is really useful prop that I overlooked and it doesn't require a lot of changes.

**Comment by mayank99** [comment]
> It is very inconvenient using `onKeyDown`, `onPaste`, also I think there is more events that you need to handle, I don't remember now. And it seems like `onValueChange` is really useful prop that I overlooked and it doesn't require a lot of changes.

@bentleyvk Do you plan to look into this? If not, we should close this issue as `wontfix`.
