### ISSUE TITLE
Header thumbnail is displaying at a smaller size than expected

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI-react#447]
#### Describe the bug (actual behavior)
When the header is in the large size, if a thumbnail / photo is available it only displays at 16x16.
![Screen Shot 2021-11-29 at 9 40 11 AM](https://user-images.githubusercontent.com/849817/143887700-d89de59d-c935-48ee-abf3-86c5cdba8ba2.png)

#### Expected behavior
When the header is in the large size, the thumbnail / photo should take the full 24x24 space.  It is displaying properly in [the HTML/CSS demo page](https://itwin.github.io/iTwinUI/backstop/minified/header.html).
![Screen Shot 2021-11-29 at 9 41 32 AM](https://user-images.githubusercontent.com/849817/143887928-9c15c3e1-715a-4e3b-9b9a-67c67718a37e.png)

**Comment by elephantcatdog** [comment]
This is fixed in Adam's header PR: https://github.com/iTwin/iTwinUI-react/pull/755
