### ISSUE TITLE
Column manager for iTwin UI React Table

### ISSUE THREAD

**Issue by nehalaho** [iTwin/iTwinUI-react#462]
#### Feature
Column Manager: It would be good to have a way to hide columns, edit column names and rearrange column ordering.
Most important feature being hiding/showing columns for a user. Such that the settings persist for a user.

#### Examples

![image](https://user-images.githubusercontent.com/9084735/144873151-124f3984-ff06-48b6-87b4-5576f5454f82.png)

**Comment by veekeys** [comment]
Hey @nehalaho 
If you havent noticed, just informing that column manager is already available.
You can find the example in here:
https://itwin.github.io/iTwinUI-react/?path=/story/core-table--column-manager
