### ISSUE TITLE
Allow tables to disable selection for specific rows

### ISSUE THREAD

**Issue by ChrisBAtBentley** [iTwin/iTwinUI-react#472]
#### Feature
It would be nice to have the ability to disable only the checkbox in individual rows so that users can still use subcomponents but cannot select the given row. Currently, it's all or nothing with disabling rows.

#### Examples
When checkbox is disabled, selection does not work on it, but all other elements in the row should work.

**Comment by bentleyvk** [comment]
As a temporary workaround you can copy paste checkbox column code from here https://github.com/iTwin/iTwinUI-react/blob/main/src/core/Table/hooks/useSelectionCell.tsx#L19 and handle disabled state yourself.

**Comment by bentleyvk** [comment]
Hey, it is finally ready in [v1.36.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.36.0) 🎉
Here is the [example](https://itwin.github.io/iTwinUI-react/?path=/story/core-table--customized-columns) with all available combinations.
If you need help, don't hesitate to ask!
