### ISSUE TITLE
Table sorting is lost when InfoPanel is opened

### ISSUE THREAD

**Issue by klopez213** [iTwin/iTwinUI-react#496]
#### Describe the bug (actual behavior)
When user sorts a table column and opens an InfoPanel, the sorting is lost.

#### Expected behavior
Retain the table sorting

#### Reproduction
Link to a minimal repro: [https://codesandbox.io/s/informationpanel-kfxd4](https://codesandbox.io/s/informationpanel-kfxd4)

##### Steps to reproduce
1. Sort the Name column descending order.
1. Click View.

**Comment by veekeys** [comment]
Hi @klopez213 
Can you double check if you are using version 1.27.1 or newer? I think it might be fixed with this #487

**Comment by klopez213** [comment]
@veekeys Hi, my sample in codesandbox.io is using 1.28 and still reproducible.

**Comment by veekeys** [comment]
@klopez213 could you add the link to the sample there?

**Comment by klopez213** [comment]
@veekeys  I'm sorry. I thought I added the link when I created the defect: [codesandbox](https://codesandbox.io/s/informationpanel-kfxd4)

**Comment by veekeys** [comment]
@klopez213 Seems memoizing the data and columns helped. As in all our stories, we always recommend to memoize those parts in table info panel made those to be recreated and table as a result rerendered.

https://codesandbox.io/s/informationpanel-forked-nnrp3

**Comment by klopez213** [comment]
Thank you @veekeys. That seems to work.
