### ISSUE TITLE
Pointer actions not working with slider

### ISSUE THREAD

**Issue by taharaza16** [iTwin/iTwinUI-react#511]
#### Describe the bug (actual behavior)
We encountered a specific bug in the iTwin-React Slider component during development. This component overrides the default behavior of pointer move event which means that we are not able to perform default pointer actions such e.g. selecting text when the slider is in the DOM.I am unable to select text after adjusting slider value. As seen in the gif below:
![chrome-capture (1)](https://user-images.githubusercontent.com/16437355/149929792-1cf67dfe-e1c1-43f5-8581-d02c6edfcda8.gif)

#### Expected behavior
Adjusting the slider should not effect pointer actions in other elements. 

#### Reproduction
[Link to a minimal repro: ](https://codesandbox.io/s/itwinui-react-example-forked-kb7oj?file=/src/App.tsx)

##### Steps to reproduce
1. Select Text (works fine)
1. Adjust Slider (triggers bug)
1. Select Text Again (doesn't work)

**Comment by mayank99** [comment]
Since we are using similar event handling in `ColorPicker` too, this issue exists there as well. Might be able to fix the two together
![slide](https://user-images.githubusercontent.com/9084735/149954388-794b895a-618b-4554-b94a-19adf13a88f3.gif)

**Comment by FlyersPh9** [comment]
If you try to click & drag to highlight the text it does not work, however if you double click within the `<input>` it will select.  Just something I discovered while playing around with the sandbox.
