### ISSUE TITLE
Table: onSelect is not called when row selection is reset when data is updated

### ISSUE THREAD

**Issue by DziugasRam** [iTwin/iTwinUI-react#522]
#### Describe the bug (actual behavior)
The table doesn't call onSelect when selected rows are reset when data is updated and autoResetSelectedRows is set to true.

#### Expected behavior
onSelect should be called when selected rows are reset when data is updated and autoResetSelectedRows is set to true.

#### Additional information
It seems that the action that resets the selected rows, when table data is updated, is not being handled inside the tableStateReducer in https://github.com/iTwin/iTwinUI-react/blob/449dc4229c15b040e62395a4ab49592217e3bf13/src/core/Table/Table.tsx#L327

**Comment by bentleyvk** [comment]
Can you give a repo sandbox or screenshot how your Table props look like? Because here is simple example with selectable Table and changeable data and selection is reset: https://codesandbox.io/s/itwinui-react-example-forked-qggwp?file=/src/App.tsx

**Comment by DziugasRam** [comment]
Just noticed that my issue description is a bit off - the problem is that the onSelect handler is not getting called when the selection is reset when the data is updated

**Comment by bentleyvk** [comment]
Hey Dziugas, sorry for delayed response. We would like to leave `onSelect` callback triggered only when user does some actions. In your case you should know when data has changed and can do handle that yourself, e.g.:
```tsx
useEffect(() => {
  setSelectedItems([]);
}, [data])
```

**Comment by veekeys** [comment]
@DziugasRam could you verify, if @bentleyvk suggestion works for your case? Let us know, so we could close this issue.

**Comment by DziugasRam** [comment]
Yes, it will work for me. Although, I think that the `onSelect` prop description should be updated to make it clear that it gets triggered only on user input.

**Comment by veekeys** [comment]
Updated description as per suggestion.
