### ISSUE TITLE
Table: onBottomReached isn't getting called when the last data row is filtered out 

### ISSUE THREAD

**Issue by DziugasRam** [iTwin/iTwinUI-react#523]
#### Describe the bug (actual behavior)
onBottomReached is only called when the row that displays the last data entry appears in the viewport, which never happens if the last row is filtered out. (The last row is being determined by its index being equal to unfiltered data's length https://github.com/iTwin/iTwinUI-react/blob/449dc4229c15b040e62395a4ab49592217e3bf13/src/core/Table/Table.tsx#L658, which doesn't work when filters are applied)

#### Expected behavior
onBottomReached should be called when the bottom of the table is reached, even when filters are applied.

**Comment by veekeys** [comment]
Hey @DziugasRam 

This is fixed in @itwin/itwinui-react@1.35.0
