### ISSUE TITLE
Tooltip: does not automatically hide on content scroll

### ISSUE THREAD

**Issue by AntonAI** [iTwin/iTwinUI-react#529]
#### Describe the bug (actual behavior)
When using the Tooltip component with the default hover trigger, if the tooltip is open and the content containing the anchor element is scrolled vertically or horizontally, the tooltip itself will scroll with the content, into other areas of the DOM.

#### Expected behavior
I would expect the tooltip to hide when the content is scrolled and its anchor element is no longer positioned under the mouse cursor.

#### Reproduction
https://codesandbox.io/s/itwinui-react-example-tooltip-bug-nvrlr

##### Steps to reproduce
1. Add a tooltip to an anchor element, for example, a button
2. Place the anchor element inside a scrollable container
3. Hover over the anchor element to show the tooltip, then scroll the content with the mouse wheel or trackpad
4. Observe tooltip contents move up/down or left/right and stay visible, instead of hiding

#### Additional information
See attached recording for this happening inside an iTwin application, with undesirable UI effects (tooltip contents overflowing into other areas of the UI).

https://user-images.githubusercontent.com/10566684/151457414-3b5b8651-2ebb-4aaa-91b7-c3403af261a6.mov

**Comment by mayank99** [comment]
@AntonAI This should be fixed in iTwinUI-react v1.31.0
