### ISSUE TITLE
Tooltips appearing off screen when used inside of modals

### ISSUE THREAD

**Issue by AroSaneD** [iTwin/iTwinUI-react#532]
#### Describe the bug (actual behavior)
When using tooltips from inside a modal, the tooltip doesn't appear on screen. 

#### Expected behavior
Tooltips should appear next to elements inside of modals.

#### Reproduction
Link to a minimal repro: https://stackblitz.com/edit/react-684c2g?file=src/App.js
Code:
```
<Modal isOpen={true} title="test dialog">
    <Tooltip content="test tooltip" placement="top" visible={true}>
        <button>hover over here</button>
    </Tooltip>
</Modal>
```

##### Steps to reproduce
1. Create a modal with a tooltip element inside
1. Hover mouse over element (or make tooltip always visible)
1. Notice that no tooltip appears

#### Additional information
Checked on versions 1.29.3 and 1.27.0

Trying to debug, it seems like the tooltip element gets created and is visible, but checking the transform field of the tooltip root (data-tippy-root), it has a large negative y value, making the element go off screen.

Edit:
The FAQ mentions about parent containers with absolute positioning causing problems, and it seems such is the case here as well, since appending to document body seems to fix it. 

So I guess this is expected behavior then? And since I'm guessing this isn't an uncommon situation/requirement, might this be worth mentioning or adding an example in the demo website?

**Comment by mayank99** [comment]
Hi @AroSaneD 👋 thanks for the issue.

> appending to document body seems to fix it.
>
> So I guess this is expected behavior then? And since I'm guessing this isn't an uncommon situation/requirement, might this be worth mentioning or adding an example in the demo website

You are right, this is "expected behavior" and `appendTo={() => document.body}` is the recommended workaround. We are considering making that option the default to mitigate these issues. See #514
