### ISSUE TITLE
itwin-react Select component stop rendering when option string is too long

### ISSUE THREAD

**Issue by mdastous-bentley** [iTwin/iTwinUI-react#535]
#### Describe the bug (actual behavior)
When a single string doesn’t fit the size of the component, the whole component stop displaying strings.
The behavior is a bit strange, if I got a very long string like ‘OpenXXXXXXXXXXXXXXXXXXXXXXXXXXXX’ it works as expected
![image](https://user-images.githubusercontent.com/8309609/152379811-8d011572-58ee-486e-bc0f-9a684ac06e42.png)

However if I use ‘Open Street Map’, the component refuse to open:
![image](https://user-images.githubusercontent.com/8309609/152379998-53ee663a-02e8-4e8a-a74b-9b6f2839166c.png)

 
I didn’t try to implement my own render to fix the issue.

**Comment by mayank99** [comment]
Hi @mdastous-bentley Could you provide more info? It's not clear from your description what your issue is.

**Comment by mdastous-bentley** [comment]
@mayank99 Please take a look at this [sandbox](https://www.itwinjs.org/sandboxes/MichelDastous/simple_backgroundmap)

Drag the 'Background Map' widget over the viewport to make it float.  The 'Provider' select wont open until you make it large enough:
![image](https://user-images.githubusercontent.com/8309609/152594285-026809a3-1efc-4250-a96e-4944456e753f.png)

**Comment by mayank99** [comment]
Ok I see. These clipping issues happen because of the absolutely positioned widget. You can work around this by adding `popoverProps={{ appendTo: () => document.body }}` to Select. This is documented in our [FAQ](https://github.com/iTwin/iTwinUI-react/wiki/FAQ#:~:text=appendto%3D%7B()%20%3D%3E%20document.body%7D)

**Comment by mdastous-bentley** [comment]
Thanks, that fix my issue!

**Comment by mayank99** [comment]
@mdastous-bentley This is now fixed in 1.32.0 so you can remove the workaround.
