### ISSUE TITLE
Toasts: `toaster.closeAll()` does not work just before adding a new toast.

### ISSUE THREAD

**Issue by Juliakas** [iTwin/iTwinUI-react#57]
#### Environment
- __Package version(s)__: 1.4.0
- __Operating System__: Microsoft Windows 10 Enterprise
- __Browser name and version__: Mozilla Firefox 88.0.1 (64-bit)

#### Code Sandbox
Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/itwinui-react-example-son74)): https://codesandbox.io/s/itwinui-react-example-forked-hcymp?file=/src/App.tsx

#### Steps to reproduce
1. Inspect code, notice `toaster.closeAll()` in "Add toast" click handler.
1. Click button "Add toast" several times.

#### Actual behavior
Multiple toasts appear.

#### Expected behavior
Last shown toast should be closed before generating next toast.

#### Additional information
For some reason `toaster.closeAll()` function does not close toasts if it is used just before adding a new toast.
On the other hand closing all toasts on a separate occasion (by clicking "Close all" button) does work as expected.

**Comment by veekeys** [comment]
If the bug you are describing is that Toasts are stacking, that is intended.
If you want to achieve that only 1 toast is visible, you need to call closeAll public method yourself, before adding new one.

**Comment by Juliakas** [comment]
> 
> 
> If the bug you are describing is that Toasts are stacking, that is intended.
> If you want to achieve that only 1 toast is visible, you need to call closeAll public method yourself, before adding new one.
> 
> EDIT: ok, now I understood. Need to read the repro code before...

Yes - so I edited repro steps now to be more clear.

**Comment by veekeys** [comment]
> > If the bug you are describing is that Toasts are stacking, that is intended.
> > If you want to achieve that only 1 toast is visible, you need to call closeAll public method yourself, before adding new one.
> > EDIT: ok, now I understood. Need to read the repro code before...
> 
> Yes - so I edited repro steps now to be more clear.

Yeah thanks. I am working on toasts right now and tested same flow, it works correct. So this should be fixed together with this:
#54
