### ISSUE TITLE
Table: After resizing any column, horizontal scrollbar appears

### ISSUE THREAD

**Issue by bentleyvk** [iTwin/iTwinUI-react#581]
Go to this story https://itwin.github.io/iTwinUI-react/?path=/story/core-table--resizable-columns
Resize any column.
Horizontal scrollbar appears.

It might be related with these changes https://github.com/iTwin/iTwinUI/pull/417

**Comment by mayank99** [comment]
Yup, I meant to create this issue 3 months ago but forgot 😅  I faced this same issue when working on the [synchronization-report](https://github.com/iTwin/synchronization-report-react), and ended up disabling column resizing.
