### ISSUE TITLE
Margin Prop for Typography Components

### ISSUE THREAD

**Issue by CadenAustin** [iTwin/iTwinUI-react#60]
#### Feature
At the moment to strip the bottom margin from typography you have to override it using css, I think it would be nice to have a prop for typography components that determines if margin is applied to the text.

#### Examples
A Boolean prop like:
`<Header useMargin={true/false} />` 
or maybe a prop to set your own margin value:
`<Header marginSize={value} />`

**Comment by mayank99** [comment]
Not sure I understand the benefit of a margin prop.

You can already do this:
```jsx
<Headline style={{ margin: 0 }} />
```
