### ISSUE TITLE
DateRangeFilter for table working strange.

### ISSUE THREAD

**Issue by sakPalhani** [iTwin/iTwinUI-react#600]
#### Describe the bug (actual behavior)
The date range filter not working as expected.
#### Expected behavior
The filter should show all the records From - To date

#### Reproduction
https://codesandbox.io/s/datefilterexample-wvh38u?file=/src/App.js

##### Steps to reproduce
1. filter from 3/5/2022 to 3/5/2022 shows empty records.
2. filter from 3/4/2022 to 3/5/2022 shows records for 3/4/2022 and 3/5/2022 but not all. I have added 3 records for 3/4/2022 and 6 for 3/5/2022. 
![image](https://user-images.githubusercontent.com/102308810/159952570-75239e3f-1044-4195-a1d3-28d1a13dc6cd.png)
3. Filter only from 3/5/2022 not return all records.
![image](https://user-images.githubusercontent.com/102308810/159952989-efaca9f6-95f3-4e82-87b6-2308e0bb0b73.png)
4. same For only To

**Comment by bentleyvk** [comment]
Fixed in [v1.34.2](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.34.2) 🌻

**Comment by sakPalhani** [comment]
Thank You!!!
