### ISSUE TITLE
Resizable and Movable Modal Dialog

### ISSUE THREAD

**Issue by jason-crow** [iTwin/iTwinUI-react#614]
#### Feature
Requesting the Modal Dialog support configuration to enable it to be movable and resizable from user interaction

#### Examples
Example dialog:
![image](https://user-images.githubusercontent.com/25822334/161553336-13f78d52-6e73-47f4-8809-612635d7efdb.png)
 Would want such a dialog to be draggable from the header to move and from the corner drag be resized. This would be an optional configuration  that would also prevent the background overlay from showing

**Comment by bentleyvk** [comment]
It is finally implemented in [v1.46.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.46.0) 🚀
