### ISSUE TITLE
Table: Shift Click Support

### ISSUE THREAD

**Issue by elephantcatdog** [iTwin/iTwinUI-react#632]
Table supports control-click for selecting multiple rows. We should add support for shift-click, which would allow users to select a range of rows by shift-clicking the first and last elements in the group.

**Comment by andriusgv** [comment]
Just want to mention, that this feature is really needed by the SYNCHRO Modeler team.

**Comment by rohan-kadkol** [comment]
@andriusgv, @HaveSpacesuit, @GintV, SYNCHRO Modeler team

We just released [v1.46.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.46.0) with this shift click feature! 🚀
