### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI-react#633]
CRA and create-vite ship with react 18, which our package.json is not compatible with, so `npm install` fails.
<img width="541" alt="image" src="https://user-images.githubusercontent.com/9084735/164484879-3d1284c6-1571-4fa1-9e37-502a61673e81.png">

### Action items

- [ ] Update peer deps react version in package.json ‼️
- [ ] Update react version in dev deps (will need to use sb 6.5 and testing lib 13)
- [ ] Update any components that are using old APIs (e.g. `ReactDOM.render` in `Toaster.tsx`)
- [ ] Check components in new `StrictMode` (e.g. in vite test app)

**Comment by bentleyvk** [comment]
> Update any components that are using old APIs (e.g. ReactDOM.render in Toaster.tsx)

Won't this break old React versions?

**Comment by mayank99** [comment]
> > Update any components that are using old APIs (e.g. ReactDOM.render in Toaster.tsx)
> 
> Won't this break old React versions?

I think we could keep backwards compatibility somehow. In this case, a simple fix could be to use `createPortal`.

**Comment by bentleyvk** [comment]
I think we also should test on both React versions. But not sure whether just unit tests or visual tests too.
