### ISSUE TITLE
Combobox onChange doesn't honor updated dependencies

### ISSUE THREAD

**Issue by klopez213** [iTwin/iTwinUI-react#635]
#### Describe the bug (actual behavior)
When dependencies change in the `useCallback()` , combobox doesn't honor this update.

#### Expected behavior
Combobox onChange should use the updated dependencies.

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/combobox-onchange-noformik-t55umm?file=/src/App.tsx

##### Steps to reproduce
1. Select a skill in Combobox skill.
1. Verify skill is set.
1. Select the same skill.

Expected Result: It should show the alert that the user selected the same skill.
Actual Result: It re-sets the skill.

##### Additional information:
Didn't check if `onBlur` behaves the same way or not.

**Comment by mayank99** [comment]
Thanks for the issue @klopez213 this is now fixed in 1.37.1 🚀
