### ISSUE TITLE
Alert: Please export type for AlertProps.type

### ISSUE THREAD

**Issue by DanEastBentley** [iTwin/iTwinUI-react#65]
Instead of this inline type for AlertProps.type:

```tsx
    /**
     * Type of the alert.
     * @default 'informational'
     */
    type?: 'positive' | 'warning' | 'negative' | 'informational';
```

Can the type be exported:

```tsx
export type AlertType = 'positive' | 'warning' | 'negative' | 'informational';

export type AlertProps = {
  /**
   * Type of the alert.
   * @default 'informational'
   */
  type?: AlertType;
```

We have introduced a function to convert our "MessageSeverity" enum to the Alert type:
```tsx
export function getAlertType(severity: MessageSeverity): string {. . .
```
```tsx
const alertType = getAlertType(severity);
```

We would rather use an exported type rather than a string as the return type. The string causes us to have to use "as any" in our Alert component usage:

```tsx
<Alert type={alertType as any} onClose={handleClose}>
```

**Comment by mayank99** [comment]
Hi Dan,

I think the problem is that you are explicitly telling Typescript that your function returns a string.

```
export function getAlertType(severity: MessageSeverity): string {
                                                         ^^^^^^
```

You should be able to remove `: string` and rely on TS to infer the type correctly since this is a simple use case. If that doesn't help, you can also try `const` assertion (introduced in [TS 3.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions)).

Does that work for you?

**Comment by mayank99** [comment]
After some more playing around, it seems the `string` type comes from the enum itself, so that won't work.

Try this:
```ts
type CustomAlertType = keyof { [key in keyof typeof MessageSeverity]: string };
```

**Comment by DanEastBentley** [comment]
I was able to solve it by using this:

```tsx
import { MessageSeverity } from "@bentley/ui-core";

/** @internal */
export type AlertType = "positive" | "warning" | "negative" | "informational" | undefined;

/** @internal */
export function getAlertType(severity: MessageSeverity): AlertType {
  let alertType: AlertType;

  switch (severity) {
    case MessageSeverity.Information:
      alertType = "informational";
      break;
    case MessageSeverity.Warning:
      alertType = "warning";
      break;
    case MessageSeverity.Error:
    case MessageSeverity.Fatal:
      alertType = "negative";
      break;
    case MessageSeverity.None:
    default:
      alertType = "positive";
      break;
  }

  return alertType;
}
```

With that change, the "as any" is not required. However, I must note that requiring a consumer to define the AlertType type in this manner is not ideal.

**Comment by mayank99** [comment]
The problem there again is using `let` to create a variable, so Typescript infers it as a string at first assignment.

Directly returning those string literals works:
```ts
export function getAlertType(severity: MessageSeverity) {
  switch (severity) {
    case MessageSeverity.Information:
      return "informational";
    case MessageSeverity.Warning:
      return "warning";
    case MessageSeverity.Error:
    case MessageSeverity.Fatal:
      return "negative";
    case MessageSeverity.None:
      return "positive";
    default:
      return undefined;
  }
}
```
![image](https://user-images.githubusercontent.com/9084735/118528803-c953bc80-b710-11eb-9358-7172d79bd682.png)

We want to avoid exporting types where not needed. If we export this, it sets the precedent for exporting other similar union types in the future.
