### ISSUE TITLE
Support multi select for combobox

### ISSUE THREAD

**Issue by jfisher-bentley** [iTwin/iTwinUI-react#650]
#### Feature
Be able to select multiple values from a combobox and have them appear as tags which can be removed individually.

#### Examples
![image](https://user-images.githubusercontent.com/86431877/166477976-10173dff-99c1-452f-ab12-e7ff8ec21d29.png)
![image](https://user-images.githubusercontent.com/86431877/166478017-4e70e439-5c44-40a6-b389-260e3bb58a5c.png)

**Comment by bentleyvk** [comment]
Duplicate https://github.com/iTwin/iTwinUI-react/issues/344
