### ISSUE TITLE
Virtualization disables horizontal scroll

### ISSUE THREAD

**Issue by gioeau** [iTwin/iTwinUI-react#676]
#### Describe the bug (actual behavior)
When virtualization is enabled and table is wider than its parent, no horizontal scroll is enabled.

#### Expected behavior
Horizontal scroll should be visible and the table should be scrollable.

#### Reproduction
https://codesandbox.io/s/itwinui-react-minimal-example-forked-p1q6ih?file=/src/App.tsx

#### Additional information
VirtualScroll sets div style to `overflow: 'hidden'`, which causes the issue.

**Comment by gioeau** [comment]
I found another issue that seems to be directly related to this one:
When creating an empty table and adding elements to it, **vertical** scrollbar appears and works as intended.
However, after closing and opening the same table with already existing elements, the scrollbar doesn't appear anymore and not all elements are displayed. Seems to be caused by the same `overflow` setting.

**Comment by mayank99** [comment]
@gioeau The original bug has now been fixed in v1.40.1. Can you verify? And if the second bug still exists, can you open a new issue (with a sandbox)? Thanks.

**Comment by gioeau** [comment]
Looks good to me, thanks for the fix!
