### ISSUE TITLE
Table: Hide checkbox tooltips from React-Table

### ISSUE THREAD

**Issue by ghost** [iTwin/iTwinUI-react#684]
The table exposes title tooltips on checkboxes that are not customizable. I suspect it is best to overwrite these tooltips to prevent any tooltip from showing on the checkboxes, though perhaps some users may be interested in a way to pass their own customized `<Checkbox>` component as the input.

![image](https://user-images.githubusercontent.com/26410416/169573959-2784292a-770a-48e1-abb7-0d50a2e39d22.png)
https://codesandbox.io/s/itwinui-react-minimal-example-forked-g2jiiq?file=/src/App.tsx

The title looks like it is manually overridable with the [React-Table props](https://react-table.tanstack.com/docs/api/useRowSelect#row-properties).

**Comment by veekeys** [comment]
This is fixed with [1.40.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.40.0)
