### ISSUE TITLE
ComboBox: Infinite loop

### ISSUE THREAD

**Issue by Guillar1** [iTwin/iTwinUI-react#697]
#### Describe the bug (actual behavior)
Externally changing the controlled value of the ComboBox is not respected or an infinite loop occurs. 

#### Reproduction
https://codesandbox.io/s/itwinui-react-example-forked-v8pllg?file=/src/App.tsx

**Comment by JonasDov** [comment]
We are facing the same issue, and need a fix ASAP.

**Comment by mayank99** [comment]
This is fixed and released in 1.41.0 but you'll need to make sure to memoize your options. We are still investigating if it's possible to avoid the infinite loop without memoizing.
