### ISSUE TITLE
Table: Crash when leaving empty editable cell

### ISSUE THREAD

**Issue by S-Bra** [iTwin/iTwinUI-react#703]
#### Describe the bug (actual behavior)
Crash when using "tab" key or mouse click to leave a empty editable cell

**Note:  Working in Firefox, Crashing in Chrome**

#### Reproduction
Use story book "editable" example

##### Steps to reproduce
1. Enter "Description1" cell
2. Remove its content
3. Press "Tab" key or click outside to leave the cell

**Comment by veekeys** [comment]
Hello @S-Bra,
This should be fixed with [v1.41.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.41.0)
