### ISSUE TITLE
Not able to add icon in FooterElement

### ISSUE THREAD

**Issue by tmmehta5** [iTwin/iTwinUI-react#705]
I'm using Footer component in my react application. I'm creating a custom footer passing FooterElement[] to customElements prop of Footer component. I want to add an icon at the start of the footer. But the definition for FooterElement doesn't allow to do so. It accepts only following:
type FooterElement = {
    title: string;
    url?: string | undefined;
    key?: keyof TitleTranslations | "copyright" | (string & Record<never, never>) | undefined;
}

#### Steps to reproduce
1. Write footer with Footer component like - `<Footer className="footer-class" customElements={() => footerElement} />`
1. Create an array of footerElement as -
`const footerElement: FooterElement[] = [
    {
      title: "xyz",
      url: "url to xyz"
    },
    {
      title: "abc",
      url: "url to abc"
    }    
  ];`

#### Expected behavior
My requirement if that this array should accept app icon.
So, I want above array to be like-
`const footerElement: FooterElement[] = [
    {
      icon:<svgIcon />
    },
    {
      title: "xyz",
      url: "url to xyz"
    },
    {
      title: "abc",
      url: "url to abc"
    }    
  ];`

@FlyersPh9

**Comment by FlyersPh9** [comment]
iTwinUI team: if a user places an SVG in our footer currently the icon is not vertically centered.  Should we update the CSS to handle this?
![Screen Shot 2022-06-08 at 12 11 23 PM](https://user-images.githubusercontent.com/849817/172665685-6fb08f05-030e-4bc4-aac1-3dbca77a7688.png)

**Comment by veekeys** [comment]
Never thought about image in footer..
@tmmehta5 do you have a mockup how it is supposed to look like with the image? Or what kind of image is expected there.

**Comment by mayank99** [comment]
> iTwinUI team: if a user places an SVG in our footer currently the icon is not vertically centered. Should we update the CSS to handle this? ![Screen Shot 2022-06-08 at 12 11 23 PM](https://user-images.githubusercontent.com/849817/172665685-6fb08f05-030e-4bc4-aac1-3dbca77a7688.png)

That should be left upto the user imo.

**Comment by tmmehta5** [comment]
@veekeys The image of area under which product is being marketed. For example, iTwinJS. 
![image](https://user-images.githubusercontent.com/107065872/172759171-feda69e5-65c1-484c-af12-954b255dd6a1.png)
