### ISSUE TITLE
Combobox: Auto select text on selection

### ISSUE THREAD

**Issue by jfisher-bentley** [iTwin/iTwinUI-react#714]
#### Feature
When an option was previously selected and the combobox is selected again, the text with the currently selected option should be selected so the user can just start typing to search for another option instead of requiring them to hit Ctrl-A first. Or at least should be an option to have it work this way.

#### Examples
![image](https://user-images.githubusercontent.com/86431877/174070705-6898e87a-a4fc-46db-97b4-87a420e6cf0b.png)
Then simply clicking the combobox would result in the text being selected already
![image](https://user-images.githubusercontent.com/86431877/174070907-f59240ba-44b3-4983-a67a-d74c71ae497a.png)

**Comment by mayank99** [comment]
Hi @jfisher-bentley, thanks for the feature request. Your described behavior would not be desirable in all cases so I do not think we would add it to our component. However, you can easily achieve this on your end by calling `.select()` in the input's `onFocus` handler. Hope that helps.

```diff
   <ComboBox
      options={countriesList}
      inputProps={{
        placeholder: 'Select a country',
+       onFocus: (e) => e.currentTarget.select(),
      }}
   />
```

**Comment by jfisher-bentley** [comment]
Works perfect. @mayank99 thanks for the suggestion
