### ISSUE TITLE
Importing itwinui-react components in vitest environment results in an error

### ISSUE THREAD

**Issue by AroSaneD** [iTwin/iTwinUI-react#727]
#### Describe the bug (actual behavior)
Importing a component from this library in vitest environment results in an error. More exactly:
```
SyntaxError: Unexpected token '{'
 ❯ wrapSafe ../../../../../../../internal/modules/cjs/loader.js:1001:16
 ❯ Module._compile ../../../../../../../internal/modules/cjs/loader.js:1049:27
 ❯ Object.Module._extensions..js ../../../../../../../internal/modules/cjs/loader.js:1114:10
 ❯ Module.load ../../../../../../../internal/modules/cjs/loader.js:950:32
 ❯ Function.Module._load ../../../../../../../internal/modules/cjs/loader.js:790:12
 ❯ Module.require ../../../../../../../internal/modules/cjs/loader.js:974:19
 ❯ require ../../../../../../../internal/modules/cjs/helpers.js:101:18
 ❯ Object.<anonymous> ../../common/temp/node_modules/.pnpm/@itwin/itwinui-react@1.40.1_react-dom@16.14.0+react@16.14.0/node_modules/@itwin/itwinui-react/cjs/core/utils/hooks/useTheme.
 ❯ Module._compile ../../../../../../../internal/modules/cjs/loader.js:1085:14
 ❯ Object.Module._extensions..js ../../../../../../../internal/modules/cjs/loader.js:1114:10
```

#### Expected behavior
Running tests through vitest should be able to import itwinui-react components.

#### Reproduction
https://stackblitz.com/edit/github-w9fjy7-cacfzq?file=package.json,src%2Fitwinui%2Fimport-test.test.tsx

Commenting out the `<Button>Itwinui button</Button>` line in the linked file will cause the test to pass.

##### Steps to reproduce
1. Setup a react project with vitest as the test runner
1. Import a `itwinui-react` component from a vitest test
1. Notice the error

#### Additional information
I tried digging into possible problems that could be causing this, and inspecting the line where this failed in `useTheme`, it's failing on an import of a css file. It seems like this is a known issue on the vitest github page: https://github.com/vitest-dev/vitest/issues/496

And according to the discussion there, it seems like just adding the newly supported `exports` field in to the package.json file of library resolves this problem. 

To check this, I tried modifying the `package.json` file in my node_modules folder, and indeed, afterwards importing and rendering of the components in vitest then work.

The working package.json looked as so: 
```
{
  "name": "@itwin/itwinui-react",
  "version": "1.40.1",
  "author": "Bentley Systems",
  "license": "MIT",
  "main": "cjs/index.js",
  "module": "esm/index.js",
  "typings": "cjs/index.d.ts",
  "exports": {
    "import": "./esm/index.js"
  },
  ...
```

**Comment by mayank99** [comment]
@AroSaneD Thank you for the issue. I was reading up on export maps and didn't find anything about using `"import"` as the key; it looks like the keys should be relative paths (starting with `.`).

https://nodejs.org/api/packages.html#package-entry-points

Are you sure your fix worked? If we were to add export maps, we would probably map our paths correctly (something like below). Would this still fix your issue?
```js
"exports": {
  ".": "./esm/index.js",
  "/*": "./esm/*"
}
```

**Comment by bentleyvk** [comment]
I was trying to add `exports` field to iTwinUI-react package that it wouldn't cause breaking changes for others but I could do it.
Here is combinations that I tried (and remember):
`"./esm/*": "./esm/*.js"`,
`"./esm/*": "./esm/*"`,
`"./esm/": "./esm/"`,
`"./esm": "./esm"`,
`"./esm/*/*": "./esm/*/*"`,
`"./esm/*": "./esm/*/*.js"`,
`"./esm/*": "./esm/*.js"`,
`"./esm/*/*": "./esm/*/*.js"`,
`"./esm/*.js": "./esm/*.js"`,
and a big part of combinations with this one:
```
"./esm/": {
  "import": "./esm/",
  "require": "./esm/"
}
```
I always had `esm` and `cjs` inside `exports`.

**Comment by Woyken** [comment]
Ran into the same issue.
It seems vitest is trying to import CJS by default, and in node environment .css files don't make much sense.
Changed package.json to have main entrypoint to ESM and all works fine
```diff
{
  "name": "@itwin/itwinui-react",
  "version": "1.45.0",
  "author": "Bentley Systems",
  "license": "MIT",
-  "main": "cjs/index.js",
+  "main": "esm/index.js",
  "module": "esm/index.js",
  "typings": "cjs/index.d.ts",
  ...
}
```
But it looks like standard practice to set "main" to common js entry.
Proper solution seems to be through exports.

Found a workaround for now:
import everything from esm module directly "@itwin/itwinui-react/esm"
```diff
- import { DatePicker } from "@itwin/itwinui-react";
+ import { DatePicker } from "@itwin/itwinui-react/esm";
```
Vitest seems to work with this

**Comment by veekeys** [comment]
@bentleyvk do you still have a branch or something, where you could test something like this?

```
"exports": {
    ".": {
        "import": "./esm/index.js",
        "require": "./cjs/index.js"
    },
    "./cjs/": "./cjs/"
},
```
With this combo in other package, seems like all direct imports from cjs still worked fine. 
I assume we would need to have same for esm, if we still want to allow people to import some of our inner solutions (like utils, which personally I do like).
Cause exports map is supposed to block all the imports for non exported globally modules (unless we specify otherwise)

**Comment by mayank99** [comment]
Worth mentioning: since we are now planning to do a major release (together with css v1), it might ok if existing direct imports break. I think that would be worth it for supporting ESM.

As for utils, we could expose them through a special path (e.g. `./utils/`) instead of the barrel.

**Comment by bentleyvk** [comment]
> @bentleyvk do you still have a branch or something, where you could test something like this?
> 
> ```
> "exports": {
>     ".": {
>         "import": "./esm/index.js",
>         "require": "./cjs/index.js"
>     },
>     "./cjs/": "./cjs/"
> },
> ```
> 
> With this combo in other package, seems like all direct imports from cjs still worked fine. I assume we would need to have same for esm, if we still want to allow people to import some of our inner solutions (like utils, which personally I do like). Cause exports map is supposed to block all the imports for non exported globally modules (unless we specify otherwise)

Idk what is wrong...
![image](https://user-images.githubusercontent.com/36186912/192951380-67027b66-b895-46fd-bb00-772c2cd04817.png)
![image](https://user-images.githubusercontent.com/36186912/192951403-81c81363-fe9f-4d55-894d-022737f4faa6.png)

Maybe you want to try yourself, maybe I am doing something wrong...

**Comment by veekeys** [comment]
We have found Vilius' test environment having some additional rules, which were influencing the outcome.
After cleanup and adding my suggested paths, vitest seemed fine. I have a PR with the `exports` field addition where would appreciate for you to check in your own environments @AroSaneD @Woyken @mayank99

**Comment by Woyken** [comment]
@veekeys I tested iTwinUI-react package with your changes from ```vyki/exports-field``` branch, it seems to work just fine 😁

**Comment by veekeys** [comment]
Great news, but seems our own testing apps are crashing now :DDD direct import from esm does not work for some reason...

**Comment by veekeys** [comment]
@Woyken @AroSaneD would you mind trying the config I have added in package json in my pr? This would be the final paths we want to have, I think. Some verification with different apps/tests would be appreciated
Just that fix can go only with v2, as technically it is a breaking change (i.e. some import paths from inner barrel files might not work anymore).

**Comment by mayank99** [comment]
This is now released in [v2](https://github.com/iTwin/iTwinUI-react/releases/tag/v2.0.0) 🎉
