### ISSUE TITLE
Need ability to pass props to DropdownMenu through ActionColumn

### ISSUE THREAD

**Issue by gioeau** [iTwin/iTwinUI-react#730]
#### Describe the bug (actual behavior)
Can't set className for DropdownMenu in ActionColumn in Table. Can't change its style because of this.

#### Expected behavior
Have ability to pass props to DropdownMenu through ActionColumn.

#### Reproduction
https://codesandbox.io/s/itwinui-react-minimal-example-forked-zxyp3w?file=/src/App.tsx

**Comment by veekeys** [comment]
This is needed to make menu with columns scrollable.
We either can think of setting some max-height for that or see for more reusable api.
