### ISSUE TITLE
Small: Wrong HTML tag

### ISSUE THREAD

**Issue by g-miranda** [iTwin/iTwinUI-react#734]
#### Describe the bug (actual behavior)

When `Small` is used inside another *Typography* (for example `Body`) a warning is raised:

![image](https://user-images.githubusercontent.com/30300136/178764526-22435279-dcb5-4c35-88fa-54f72a9a2413.png)

#### Expected behavior

According to [HTML standards for p](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1):

> The [P](https://www.w3.org/TR/html401/struct/text.html#edef-P) element represents a paragraph. It cannot contain [block-level elements](https://www.w3.org/TR/html401/struct/global.html#block-inline) (including [P](https://www.w3.org/TR/html401/struct/text.html#edef-P) itself).

The `<Small>` component is expected to generate the `<small>` tag.

#### Reproduction
```jsx
<Body>
  Some <Small>text</Small>
</Body>
```

#### Additional information
References:
[W3C - Paragraphs: the P element](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1)
[W3C - Block-level and inline elements](https://www.w3.org/TR/html4/struct/global.html#h-7.5.3)
[MDN Content Categories](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories)
[MDN page for `small`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/small)

**Comment by mayank99** [comment]
Hi @g-miranda, thanks for the issue. I've created #735 to fix this, however I would recommend you to use the [`<Text>`](https://itwin.github.io/iTwinUI-react/?path=/story/typography-text--polymorphic) component because it gives you more control over the rendered element through `as` prop.

```tsx
<Text variant='body' as='p'>
  Some <Text variant='small' as='small'>text</Text>
<Text>
```

**Comment by g-miranda** [comment]
Hi @mayank99. Thank you for the suggestion, I'll do that.
