### ISSUE TITLE
Swap happy and sad face icons in storybook's slider example with a custom thumb

### ISSUE THREAD

**Issue by rohan-kadkol** [iTwin/iTwinUI-react#740]
This is a **small** inconsistency: The happy and the sad icons might need to be swapped in the [storybook example of the slider with the custom thumb](https://itwin.github.io/iTwinUI-react/?path=/story/input-slider--with-custom-thumb). Usually sad gets a smaller number and happy gets a higher number. But here it is the opposite.

![image](https://user-images.githubusercontent.com/45748283/180093123-7c1c7bb7-7c84-45a4-bacb-1a8ed9321585.png)

**Comment by mayank99** [comment]
Maybe it is an indication of "How sad are you on a scale of 1-100?" 😄

Either way, this is not a bug in the component, just the example, so I've changed the label.
