### ISSUE TITLE
With two modals loaded background is scrollable

### ISSUE THREAD

**Issue by JonasDov** [iTwin/iTwinUI-react#748]
#### Describe the bug (actual behavior)
Let's say that there are two modals: modal A (parent modal), modal B (modal inside modal A). And when both of them are loaded at the same time, modal A is visible and modal B is not visible, then the background behind modal A is interactive. You can scroll up or down in the page, press some buttons.

#### Expected behavior
When modal is open, background behind the modal should not be interactive

#### Screenshots
There is a modal:
![image](https://user-images.githubusercontent.com/100586436/180795877-eeef95f0-c746-4f53-b7f0-4d24f0cb4504.png)
Inside the modalContent section there is a different modal:
![image](https://user-images.githubusercontent.com/100586436/180796136-04857cd7-0c43-4530-b52b-54261bc84a4b.png)
When only main modal is open background behind is scrollable:
![image](https://user-images.githubusercontent.com/100586436/180796566-66ce395f-52ba-4d95-aeee-8beea95eb151.png)
When both modals are open background behind main modal is not interactive, but main modal is interactive:
![image](https://user-images.githubusercontent.com/100586436/180796764-ef175d7a-60bf-450c-b19e-9d2937ec01c1.png)

**Comment by mayank99** [comment]
Hi @JonasDov, thank you for the issue!

First off: we do not recommend nesting modals from a UX standpoint. If possible, I would suggest rethinking the UX there.

But we should still support it from a technical standpoint. I think this issue is happening because the modals use the same container element for their portal. _But_ we support overriding that through the `modalRootId` prop. Can you try creating your own container with a different id and passing that to `modalRootId`? That might fix the issue.

Thanks.

**Comment by JonasDov** [comment]
Yes, I know that this is bad UX, we decided to remove it (filled out a bug, so you could know about this issue). We have found that what fixes this issue is: Instead of loading the modal and changing isOpen property, we only load the modal when the property changes. 
So instead of doing it like this:
![image](https://user-images.githubusercontent.com/100586436/180800419-5abbc0b0-3755-4fd3-921b-d6503e7d0743.png)
we do it like this:
![image](https://user-images.githubusercontent.com/100586436/180800329-cd4c593e-1e40-46b6-a897-4587d4df3f71.png)
P.S. Trying to create a new container with different id and passing it to modalRootId did not fix this.

**Comment by bentleyvk** [comment]
It is fixed in [v1.46.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.46.0) 🚀
