### ISSUE TITLE
Table: Resize after column toggle leads to distorted columns

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI-react#757]
#### Describe the bug (actual behavior)
Using a resizable table with the column manager:
* Resize a column
* Hide and then show a column with the column manager
* Resize any column - the headers no longer line up with the table data

Alternatively:
* Hide a column
* Resize any column
* Show the hidden column
* Resize any column - the headers no longer line up with the table data

This does not seem to occur if the user hasn't resized a column before unhiding a column.

#### Expected behavior
The columns should line up with the headers when resizing after using the column manager.

#### Reproduction
https://codesandbox.io/s/itwinui-react-minimal-example-forked-xbs4jm?file=/src/App.tsx
![Column alignment](https://user-images.githubusercontent.com/15036346/182210712-af260215-4f35-48c9-9a2b-1a4566e3f141.gif)

**Comment by bentleyvk** [comment]
I found even crazier steps to reproduce:
1. Hide column.
2. Resize other column.
3. Unhide previous column.
4. Press with mouse anywhere, e.g. right-click outside the table.
![table-header-shift](https://user-images.githubusercontent.com/36186912/182545696-804652f4-6b06-44e2-818b-69cf0fecc09e.gif)
