### ISSUE TITLE
Toast anchor point

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI-react#78]
#### Feature
- [x] Opening Toast & Sticky messages that are anchored to the Status Bar at the bottom of the AppUi window
- [ ] When Toast messages close automatically, they animate toward the Message Center indicator in the Status Bar
- [x] When closing a Sticky message below other messages, the remaining messages slide down
- [ ] A single Activity message can be opened and sits below other messages

#### Examples

![AppUiMessages2](https://user-images.githubusercontent.com/81580355/119144812-b3683380-ba51-11eb-8286-3ea9e855af47.gif)

**Comment by mayank99** [comment]
@DanEastBentley We are adding support for anchor point in our Toaster, which will easily address these two points:
> - Opening Toast & Sticky messages that are anchored to the Status Bar at the bottom of the AppUi window
> - When closing a Sticky message below other messages, the remaining messages slide down

However, we haven't decided (yet) how exactly to implement this part:
> - When Toast messages close automatically, they animate toward the Message Center indicator in the Status Bar

It will likely be similar to the [AppUI `animateOutTo` implementation](https://github.com/imodeljs/imodeljs/blob/master/ui/ninezone/src/ui-ninezone/footer/message/Toast.tsx#L143). Are there any "gotchas" there we should be aware of that might help us implement it quicker?

And once all that is available, we might remove the `ToastPresentation` export. Hope that works for you.

**Comment by DanEastBentley** [comment]
@GerardasB implemented the animateOutTo early in the iModel.js implementation. He may have more insight into possible improvements. 

The plan of removing the ToastPresentation after our team has had time to consume the full iTwinUI Toast system sounds good; however, I don't know what that time frame will be.
