### ISSUE TITLE
Dialog always hijacks focus

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI-react#784]
Even when `trapFocus` is set to false, using `Dialog.Main` with `isOpen={true}` causes it to focus the dialog.

This is not ideal because sometimes you don't want the focus to move. e.g. for a cookie dialog, it might not necessarily be the best move to autofocus the dialog.

The problem is likely this line:

https://github.com/iTwin/iTwinUI-react/blob/2de1c9a49ee08a7afbf58f0576f12a522cf5b7f3/packages/iTwinUI-react/src/core/Dialog/DialogMain.tsx#L73

**Comment by bentleyvk** [comment]
I guess we should only call `focus()` when `trapFocus` is `true`

**Comment by mayank99** [comment]
I think this would need to be a new prop called something like `setFocus` because there are cases where you might want to trap focus but not set focus.

Example: if you want to auto focus a button inside the dialog and also trap focus, you would do something like:

```jsx
<Dialog setFocus={false} trapFocus>
  <Button autoFocus />
</Dialog>
```
