### ISSUE TITLE
User icons: stack multiple

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI-react#80]
Multiple user icons can slightly overlap each other.
If there are too many user icons, we show X amount and then the overflow user icons are replaced with a +10 user icon.  If you interact with the last user icon (maybe hover, maybe click) you will see a dropdown menu of the remaining users.

**Comment by FlyersPh9** [comment]
I would say the non-animated user icon list is higher priority than the animated one.  There's some [documented details here](https://ux.bentley.com/itwin/components/user-icon.html#team-displays) that Virginie wrote.
![Screen Shot 2021-06-30 at 4 24 51 PM](https://user-images.githubusercontent.com/849817/124026452-b430a580-d9bf-11eb-99a1-b8f6bdc00bcd.png)
