### ISSUE TITLE
Table: `BaseFilter` isn't exported from the package

### ISSUE THREAD

**Issue by DziugasRam** [iTwin/iTwinUI-react#817]
#### Describe the bug (actual behavior)
To import `BaseFilter` you need to import it from `@itwin/itwinui-react/cjs/core/Table` instead of `@itwin/itwinui-react`

#### Expected behavior
`BaseFilter` should be exported the same way as all the other components. The component documentation mentions that it should be used to create custom filters, so its not an internal util and its meant for reuse by consumers.

**Comment by bentleyvk** [comment]
It is fixed in [v1.46.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.46.0) 🚀
