### ISSUE TITLE
Expand table on column resize

### ISSUE THREAD

**Issue by bentleyvk** [iTwin/iTwinUI-react#824]
We could have some flag that toggles resize mode like react-grid https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/#resizing-modes

### Discussed in https://github.com/iTwin/iTwinUI-react/discussions/822

<div type='discussions-op-text'>

<sup>Originally posted by **HaveSpacesuit** September  9, 2022</sup>
It is difficult to expand columns to a wide width. Currently it looks like when a column is resized, the next column loses or gains width based on the first column resize. The overall table width stays the same.

![Column resize static](https://user-images.githubusercontent.com/15036346/189432427-19eb901a-f641-4cf3-84ee-48a3ed4f0778.gif)

It would be nice to expand/shrink the entire table width when a column is resized. If I make column A bigger, I likely do not want to make column B smaller.

This should work in situations when the table has horizontal scroll and does not have horizontal scroll - adding or removing the scroll as needed.

Here is a sandbox showing that it is not easy to expand a column past the point where the next column is at minimum width. There are examples with and without horizontal scroll. (I usually have the last column width set to undefined in order to allow the table to fill horizontal space if the columns do not all fit.)

https://codesandbox.io/s/itwinui-react-minimal-example-forked-7wizuj?file=/src/columns.ts

![Column width scroll](https://user-images.githubusercontent.com/15036346/189432701-0fe14f6b-6464-413e-9dc2-986e561dd567.gif)
</div>

**Comment by FlyersPh9** [comment]
[This Yammer discussion](https://web.yammer.com/main/org/bentley.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMTkxNjk2MTk0Nzc3MDg4MCJ9) (internal access only) might be related.
