### ISSUE TITLE
Implement iTwinUI-CSS 1.0

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI-react#831]
iTwinUI-CSS 1.0 implementation tasks, please refer to https://github.com/iTwin/iTwinUI/wiki/v1-Migration-guide to better understand what has changed and what work is needed:

- [x] Alert
  - [feat(Alert): Class name & specificity refactor](https://github.com/iTwin/iTwinUI/pull/756/commits/97744c308387c86a827dca40187b6ea9e1b1a53d)
- [x] Avatar
  - [chore: Rename Components](https://github.com/iTwin/iTwinUI/pull/756/commits/702786b644b33ae85c4c4acba4ba6441e70c3597)
- [x] Button
  - [x] [feat(Button): Class name & specificity refactor](https://github.com/iTwin/iTwinUI/pull/756/commits/c1501a6f01ee3017247ebd08f64cd955fb2cd1ae)
  - [x] [feat(Button): Refactor split button](https://github.com/iTwin/iTwinUI/pull/756/commits/831f5278f8ab260df414c96f040300efe4c3c6ed)
- [x] Carousel
  - [fix(carousel): Dots are centered](https://github.com/iTwin/iTwinUI/pull/756/commits/a5a7ac24452571828b1234f02658b1d7d3023b9d) (Rohan)
- [x] Checkbox (Rohan)
  - [chore(Inputs): Break /inputs/ into multiple folders.](https://github.com/iTwin/iTwinUI/pull/756/commits/d5d6f1ed458f87017e3f0bcb5d180b8ebe85eb99)
- [x] Dialog
  - [x] [fix(Dialog): Add `position: fixed` as an option for dialogs](https://github.com/iTwin/iTwinUI/pull/756/commits/bf38b24cd47e7980084bc59546b73049a4a284e3) (Rohan)
  - [x] [fix: Make dialog positioned and remove unneeded styles](https://github.com/iTwin/iTwinUI/pull/756/commits/da810533f758fae1a0e8a61ad4144a88519be178) (Rohan)
- [x] Header
  - [feat(Header): Class name & specificity refactor](https://github.com/iTwin/iTwinUI/pull/756/commits/c06a1fbc6048e4e3dd7dbd9cafc3c4e11fcb10fd)
- [x] Icon (Leah)
  - [feat(Icon): Separate color from icon sizes & status color from default color.](https://github.com/iTwin/iTwinUI/pull/756/commits/dc93ec1b6575eb73522fe7bc40db55e679f5daaa)
- [x] Input (Rohan)
  - [chore(Inputs): Break /inputs/ into multiple folders.](https://github.com/iTwin/iTwinUI/pull/756/commits/d5d6f1ed458f87017e3f0bcb5d180b8ebe85eb99)
- [x] Menu
  - [x] [feat(Menu): Add CSS variable for max-height on scrollable menu](https://github.com/iTwin/iTwinUI/pull/756/commits/804c819792ec382f83a357cd855f407a6e1f5c4d) (Rohan)
  - [x] [fix(Menu): Show last element partially in .iui-scroll](https://github.com/iTwin/iTwinUI/pull/756/commits/ffbaba0c49e77b60515d9945e06e60bd0374e84a) (Rohan)
- [x] Radio (Rohan)
  - [chore(Inputs): Break /inputs/ into multiple folders.](https://github.com/iTwin/iTwinUI/pull/756/commits/d5d6f1ed458f87017e3f0bcb5d180b8ebe85eb99)
- [x] Select (Rohan)
  - [chore(Inputs): Break /inputs/ into multiple folders.](https://github.com/iTwin/iTwinUI/pull/756/commits/d5d6f1ed458f87017e3f0bcb5d180b8ebe85eb99)
- [x] Slider
  - [x] [fix(Slider): Fixed vertical & horizontal slider icons misalignment](https://github.com/iTwin/iTwinUI/pull/756/commits/18e22c39b1c9bd7dfd4d9c198c6dba33475e97a9)
  - [x] [fix(Slider): Dynamic resize of rail based on label size](https://github.com/iTwin/iTwinUI/pull/756/commits/d93f55aede62594334c4210a0a5834a44bfe8c15)
- [x] Stepper
  - [x] [chore: Rename Components](https://github.com/iTwin/iTwinUI/pull/756/commits/702786b644b33ae85c4c4acba4ba6441e70c3597)
  - [x] [feat(WorkflowDiagram): Separate workflow diagram from stepper](https://github.com/iTwin/iTwinUI/pull/756/commits/2304649e9ed9b52ae7e17330384d9321b978f73f)
- [x] Table
  - [x] [feat(Table): Class refactor](https://github.com/iTwin/iTwinUI/pull/756/commits/76704f0e3ad517ddd6aab22bb396d7e79b016ec3)
  - [x] [fix(Table): Disabled cell with monochrome icon use consistent fill color](https://github.com/iTwin/iTwinUI/pull/756/commits/29601a8e9d705161f5f170c04c14c72f1ce58172) (Rohan)
  - [x] [fix(Table): Changing start icon fill from <svg> tag](https://github.com/iTwin/iTwinUI/pull/756/commits/927254c381e81b3fdb6fe14ac44f18f744e57392) (Rohan)
- [x] Textarea
  - [feat: Remove `iui-textarea`](https://github.com/iTwin/iTwinUI/pull/756/commits/f68e9dbf9c4de0d3fdc2c09bfa5bf304f404b6da)
- [x] Workflow diagram
  - [feat(WorkflowDiagram): Separate workflow diagram from stepper](https://github.com/iTwin/iTwinUI/pull/756/commits/2304649e9ed9b52ae7e17330384d9321b978f73f)
- [x] Other
  - [x] [feat(style): Add `Noto` font family](https://github.com/iTwin/iTwinUI/pull/756/commits/478bd9e141d0448c245a1246404dcb47e63cb035)
  - [x] [chore: Review folder structure](https://github.com/iTwin/iTwinUI/pull/756/commits/6993aa2acbfbf0c156b29f4773450c0e88c13018)
  - [x] [feat: Move visually-hidden from global to utils](https://github.com/iTwin/iTwinUI/pull/756/commits/95ce58c88da1fc50d52292f3d7dced235d299adb)
  - [x] [fix(Table): Keyboard Navigation Support](https://github.com/iTwin/iTwinUI/pull/756/commits/1ea488c4d4755ebb8853db20e896af5153d3e199)
  - [x] [feat: Scope all global styles under `iui-root`](https://github.com/iTwin/iTwinUI/pull/756/commits/1a4c68c720fad85f888503735fbba2257709cbb6)
  - [x] [feat: Use itwinui-variables](https://github.com/iTwin/iTwinUI/pull/756/commits/ca42d732feda861bf3d3e10c2b358fa59ad0f419)
  - [x] [chore: Remove IE support](https://github.com/iTwin/iTwinUI/pull/756/commits/bd8cf83de230656e8c2a851d063cfbbf52926aaa) (Adam)
  - [X] [feat: Unified disabled & loading states](https://github.com/iTwin/iTwinUI/pull/756/commits/e012ec3353a875ce73ab7a5a54b90b752cdde5ea) (Greta)
  - [x] [chore: Added aliases in root for commands in css package](https://github.com/iTwin/iTwinUI/pull/756/commits/df9ff86fd78993f287aad71ca632e999d4562e06)

**Comment by mayank99** [comment]
Removing IE support (https://github.com/iTwin/iTwinUI/pull/655) is not in this list. The CSS changes in that PR won't directly affect React, but we have a few instances of IE workarounds (e.g. guarding custom properties under `CSS.supports`) that we can remove.

**Comment by mayank99** [comment]
Checking off 4 of my items (textarea, visually-hidden, scoped styles, itwinui-variables) that were handled in https://github.com/iTwin/iTwinUI-react/pull/820 and #825.

**Comment by FlyersPh9** [comment]
> Removing IE support ([iTwin/iTwinUI#655](https://github.com/iTwin/iTwinUI/pull/655)) is not in this list. The CSS changes in that PR won't directly affect React, but we have a few instances of IE workarounds (e.g. guarding custom properties under `CSS.supports`) that we can remove.

Added at the very bottom of the list.

**Comment by elephantcatdog** [comment]
I added checkboxes to items under components with multiple tasks, because some of them may be done but not all of them

**Comment by adamhock** [comment]
Checking off the following items:

- Alert: #753 
- Header: #755 
- Stepper: #769 
- Table: #749

**Comment by gretanausedaite** [comment]
Checking off Noto font change #812

**Comment by rohan-kadkol** [comment]
Checking off the two slider PRs ( [#761 (merge commit)](https://github.com/iTwin/iTwinUI/pull/756/commits/18e22c39b1c9bd7dfd4d9c198c6dba33475e97a9) and [#764 (merge commit)](https://github.com/iTwin/iTwinUI/pull/756/commits/d93f55aede62594334c4210a0a5834a44bfe8c15) ) since they only involve CSS attribute changes and hence need no changes in React

**Comment by gretanausedaite** [comment]
Button changes is in React branch #752

**Comment by rohan-kadkol** [comment]
Checking off the four items for: [chore(Inputs): Break /inputs/ into multiple folders.](https://github.com/iTwin/iTwinUI/pull/756/commits/d5d6f1ed458f87017e3f0bcb5d180b8ebe85eb99): `Checkbox`, `Input`, `Radio`, `Select`. The imports were updated by the commit https://github.com/iTwin/iTwinUI-react/commit/6d5aab34a728da71062451823eb24213c635b66d

I checked this by ensuring the imports for the React component files were pointing to the correct CSS file. There were no HTML/classname changes.

**Comment by elephantcatdog** [comment]
[fix(Table): Keyboard Navigation Support](https://github.com/iTwin/iTwinUI/pull/756/commits/1ea488c4d4755ebb8853db20e896af5153d3e199) was dealt with in #802
[chore: Rename Components](https://github.com/iTwin/iTwinUI/pull/756/commits/702786b644b33ae85c4c4acba4ba6441e70c3597) was dealt with in #773

I confirmed [chore: Review folder structure](https://github.com/iTwin/iTwinUI/pull/756/commits/6993aa2acbfbf0c156b29f4773450c0e88c13018)

**Comment by FlyersPh9** [comment]
Added [feat: Unified disabled & loading states](https://github.com/iTwin/iTwinUI/pull/756/commits/e012ec3353a875ce73ab7a5a54b90b752cdde5ea) under the Other category.

**Comment by elephantcatdog** [comment]
I confirmed [feat(Icon): Separate color from icon sizes & status color from default color.](https://github.com/iTwin/iTwinUI/pull/756/commits/dc93ec1b6575eb73522fe7bc40db55e679f5daaa)

**Comment by gretanausedaite** [comment]
Unified disabled and loading states are partly done with #869 PR (updated current loading/disabled states with new css)
Tile status and loading state will be added with #872 
Table row loading state will be added with #871

**Comment by rohan-kadkol** [comment]
Checking off [fix(Dialog): Add position: fixed as an option for dialogs](https://github.com/iTwin/iTwinUI/pull/756/commits/bf38b24cd47e7980084bc59546b73049a4a284e3) with React PR #866

**Comment by rohan-kadkol** [comment]
Checking off the following with PR #881:
  * [fix(Menu): Show last element partially in .iui-scroll](https://github.com/iTwin/iTwinUI/pull/756/commits/ffbaba0c49e77b60515d9945e06e60bd0374e84a)
  * [fix(Table): Disabled cell with monochrome icon use consistent fill color](https://github.com/iTwin/iTwinUI/pull/756/commits/29601a8e9d705161f5f170c04c14c72f1ce58172)

**Comment by rohan-kadkol** [comment]
Checking off the last item (as of now): Dialog item [fix: Make dialog positioned and remove unneeded styles](https://github.com/iTwin/iTwinUI/pull/756/commits/da810533f758fae1a0e8a61ad4144a88519be178) with PR #873

**Comment by rohan-kadkol** [comment]
Checking off [fix(Table): Changing start icon fill from tag](https://github.com/iTwin/iTwinUI/pull/756/commits/927254c381e81b3fdb6fe14ac44f18f744e57392) with PR #890
