### ISSUE TITLE
Select: Add support for data-testid to popoverProps and SelectOption

### ISSUE THREAD

**Issue by DanEastBentley** [iTwin/iTwinUI-react#85]
I could not find a way to add data-testid to the `<DropdownMenu>` through `popoverProps` or each SelectOption/`<MenuItem>`. Please provide support for data-testid in the Select component `<DropdownMenu>` and `<MenuItem>` through SelectOption.

**Comment by mayank99** [comment]
Hi Dan,

Not sure we can easily offer a nice way to add `data-` attributes to those elements through our Select props, but you can make use of the [`onCreate`](https://atomiks.github.io/tippyjs/v6/all-props/#oncreate) callback which gives you a [`PopoverInstance`](https://github.com/iTwin/iTwinUI-react/blob/main/src/core/utils/Popover.tsx#L10).

Example:
```tsx
<Select
  {...otherProps}
  popoverProps={{
    onCreate: (i) => { i.popper.firstElementChild?.setAttribute('data-testid', 'value'); },
  }}
/>
```

The `i.popper` contains the entire DOM tree that you can traverse and add attributes to.

Additionally, for `SelectOption` we have `itemRenderer` where you can return any JSX you want.

Does that work for you?

**Comment by DanEastBentley** [comment]
Not really. We've written helper functions to find a Select menu after the Select button is clicked then find one of its menu items by index or by the label text. 
https://github.com/imodeljs/imodeljs/blob/ui/itwinui-incorporation/ui/components/src/test/test-helpers/misc.ts#L51 

We can have multiple Select components within a unit test and both can be opened within the test. Since the Select's menu in the DOM is not associated with the Select component in the DOM (it's down in data-tippy-root, tippy-box and tippy-content divs), we made use of the menuClassName prop, which allows us to find the menu using the following in our helper functions:
```tsx
  let selector = `.iui-menu.${menuId}`;
  const menu = document.querySelector(selector) as HTMLUListElement;
```

This is not ideal because we're having to add a CSS class name for testing purposes. Then to find one of the menu items, we have to do some searching for the label:
```tsx
  selector = "li span.iui-content";
  const menuItems = menu.querySelectorAll(selector);
  const menuItem = [...menuItems].find((span) => span.textContent === label);
```

Once we've found the menu item, we can fire a click event to make it active:
```tsx
fireEvent.click(menuItem!)
```

We're doing all of that instead of what we used to do:
```tsx
fireEvent.change(typeSelector, { target: { value: FormatType.Station.toString() } });
```

So, these helper functions work for us, but we shouldn't really have to do all of this. And we certainly can't make a Select option active by its value because the current DOM structure doesn't contain anything about an option's value. That's why we're stuck finding select options using the index or label.

If we had data-testid support for the menu and the menu items, it might make this a little easier. But we're OK for now.

**Comment by mayank99** [comment]
> _We can have multiple Select components within a unit test and both can be opened within the test_

Oh, we are used to having only one per test (as it's trivial to do in jest). But even if you have multiple, you still don't need to use a custom class name because you can use internal ids.

Try rendering the test like this:

```tsx
<Select
  {...otherProps}
  popoverProps={{
    onCreate: (i) => { dropdownId = i.popper.id; }, // save this id somewhere
  }}
/>
```

and then, you should be able to simply do this:
```tsx
fireEvent.click(select.querySelector(".iui-select-button") as HTMLElement); // assuming you can already find `select`

fireEvent.click(document.querySelectorAll(`#${dropdownId} .iui-menu li`)?.[index]); // click using index
```

**Comment by mayank99** [comment]
We're making a change in #90 that will put the menu under the main select div, so you won't need to bother with the popper id I suggested above.

After that, you should be able to do something like:
```tsx
const select = container.querySelector(`.iui-select[data-testid=${selectId}]`)
fireEvent.click(select.querySelector('.iui-select-button'));
fireEvent.click(select.querySelectorAll('.iui-menu li')?.[index]);
```

Does that solve your problem?

**Comment by DanEastBentley** [comment]
Yes, that will help. Thanks.

**Comment by veekeys** [comment]
@DanEastBentley Release [1.6.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.6.0) is published with the Select changes. Try it out and let us now, if that solves the issue.

**Comment by DanEastBentley** [comment]
Now that the .iui-menu is within the Select component hierarchy, it is much easier to unit test. With your change the data-testid is no longer needed in the popoverProps. 

We have helper functions to find a menu/option item by index or label. The data-testid support in the SelectOption would be nice, but it's not critical.
