### ISSUE TITLE
Shift selection ignores any ctrl/checkbox/toggle selections in multi selection mode table

### ISSUE THREAD

**Issue by ainepi** [iTwin/iTwinUI-react#879]
#### Describe the bug (actual behavior)
When using multi selection mode table, clicking more than one item (using ctrl or checkbox), and then using shift selection, it ignores any other selected items and takes the first selected item as a starting point for the shift range.
![image](https://user-images.githubusercontent.com/17889303/195827505-ad626008-5989-46f7-a238-e337c7b3cfb2.png)

#### Expected behavior
Shift should take the last selected item as a starting point for range selection

##### Steps to reproduce
1. Select any row
2. Select a second row using the checkbox or ctrl
3. Use shift to select any row

##### Additional information
Related issue #880

**Comment by rohan-kadkol** [comment]
Hi Aiste, I made a PR [#886](https://github.com/iTwin/iTwinUI-react/pull/886) for your Ctrl + Shift click issue #880. For this issue, I made a [commit](https://github.com/iTwin/iTwinUI-react/commit/ecc83666d5d11bd1f94dabddb4c42282312c7e5c) on the [rohan/table-shift-click-checkbox-bug](https://github.com/iTwin/iTwinUI-react/tree/rohan/table-shift-click-checkbox-bug) branch. This is not complete but I think it implements a majority of the fix.

I could make a PR from that branch to `main`, or if you feel like it, you can make your own PR, possibly using my branch for ideas. (We encourage external contributions :slightly_smiling_face:). Please let me know what you prefer.

**Comment by rohan-kadkol** [comment]
@ainepi As we discussed via chat, I made PR #889. Feel free to comment on that PR if you have any comments/suggestions.
