### ISSUE TITLE
Input: stop event propagation

### ISSUE THREAD

**Issue by FelixGirard** [iTwin/iTwinUI-react#899]
#### Describe the bug (actual behavior)
When entering text in an Input, it may activate a tool in the active viewer (if one is open). 
For example, if I search 'e' in the Tree View, the rotation tool activate: 

![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/7445146/198399581-573c3274-58d2-44d4-b504-09f0d4e823a1.png)

#### Expected behavior
By default, I would expect an Input to stop the propagation of the event.

#### Reproduction
Link to a minimal repro: 

##### Steps to reproduce
1. Create a widget with an input.
2. Type a key that activate a tool ('e' for example)

#### Additional information
I know I can provide functions that stop the event propagation. I think it could cause confusion for anyone working in widgets, and that we probably want this more often than not.

**Comment by FelixGirard** [comment]
I would expect it to behave differently because I guess most of the use of the component is with an open iTwin Viewer. I wish there was at least an option for that in the component, to not force each team working in widgets to create their own.

**Comment by mayank99** [comment]
I think it might make more sense for iTwin Viewer shortcuts handling to take into account for what element is focused. I don't think iTwinUI, as a generic component library, should handle these specific things. Our Input is meant to be used across all kinds of applications, not just iTwin Viewer, and someone else might rely on the propagation behavior.
