### ISSUE TITLE
ComboBox dropdown opens hidden

### ISSUE THREAD

**Issue by NancyMcCallB** [iTwin/iTwinUI-react#903]
When a ComboBox is hosted in a ModelessDialog in AppUi, the dropdown opens hidden.
Link to a minimal repro: https://www.itwinjs.org/sandboxes/NancyMcCall/ComboBox%20in%20ModelessDialog

1. Push "Open Modeless Dialog" button
2. Click in the ComboBox to expand menu

Inspecting the popover shows that although the data-state is set to visible, the iui-popover class is overriding it and setting visible:hidden.
![image](https://user-images.githubusercontent.com/45079789/199277198-307a1b3c-3440-46d5-a03c-b0f05d79e565.png)

**Comment by mayank99** [comment]
I don't think this is a bug in iTwinUI. We investigated this in https://github.com/iTwin/iTwinUI-react/issues/783#issuecomment-1220757136 and found that it's happening because the modeless dialog size is 0x0.
