### ISSUE TITLE
Resizable dialogs - retaining width & height

### ISSUE THREAD

**Issue by jzbuchalski** [iTwin/iTwinUI-react#920]
#### Feature
Is it possible to provide say a unique id (per dialog), and have the width & height retained in local storage.  Even session storage would be an improvement.  Currently if you resize a dialog, close it, and reopen, it returns to the default width & height.

**Comment by mayank99** [comment]
@JoeZman Can you provide a repro where it doesn't retain width and height? If you use keep the `Dialog` in the react tree and use `isOpen` to toggle visibility, then it should retain its size.

https://user-images.githubusercontent.com/9084735/200854653-9efb7522-358e-432b-a56e-63d2045f0308.mov

**Comment by JoeZman** [comment]
Ok, I was test myself, I was in a demo this morning, and it wasn't retaining the values.  I will investigate.

**Comment by rohan-kadkol** [comment]
> Ok, I will test myself, I was in a demo call this morning, and noticed the dialogs were not retaining their values. I will investigate.

Hi @jzbuchalski, just confirming, were you able to get it working? If not, could you give some more information/repro about the case in which the dialog doesn't retain the width and height?

**Comment by jzbuchalski** [comment]
Our dialogs are not always in the DOM, so we have a backlog item (in Design Review) to retain the state of dialogs in possibly local storage.

**Comment by jzbuchalski** [comment]
For my concerns, you can close this issue.
