### ISSUE TITLE
ComboBox dropdown not visible

### ISSUE THREAD

**Issue by SStalciuss** [iTwin/iTwinUI-react#947]
#### Describe the bug (actual behavior)
ComboBox menu is not visible if it is outside of parent and one of the parents has `overflow` property set, even with boundary set to window/document.

#### Expected behavior
ComboBox menu is visible even if it is outside of a parent if boundary is set to window/document.

#### Reproduction
https://stackblitz.com/edit/react-ts-pmjwpw

##### Steps to reproduce
1. Open overlay, expand comboBox menu
2. Shrink viewport so at least a part of comboBox input would be under the right panel (then menu will be visible)
3. Expand viewport so non of comboBox input would be under right panel (menu will be hidden)

https://user-images.githubusercontent.com/53999653/202994943-0e666ff4-a735-4b11-b2fb-0582ae17987c.mp4

##### Additional information
We are using version 1.43.0. This fix would be appreciated in V1.

**Comment by gretanausedaite** [comment]
Hi!
Thanks for submitting an issue.
Your request to add it it V1 is noted and we are discussing it within the team.

**Comment by SStalciuss** [comment]
The problem is here: https://github.com/iTwin/iTwinUI-react/blob/7640e83ba0fe5d29816a98c3a506afc53a624516/packages/iTwinUI-react/src/core/utils/components/Popover.tsx#L85

This would solve my issue https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md#if-you-were-using-boundary but you are setting a modifier with name 'preventOverflow' so the one that I pass in probably gets ignored. Adding additional property to options `rootBoundary: 'document'` fixes it, so you probably need to merge passed modifiers with your own.

**Comment by SStalciuss** [comment]
Well previously I somehow managed to fix it by changing how the modifiers are passed.

Now the object look like this:
![image](https://user-images.githubusercontent.com/53999653/203817300-8da3e2b6-e655-4872-9195-9094ba297afb.png)

I thought it should look like this (and it helped):
![image](https://user-images.githubusercontent.com/53999653/203817027-297aba69-5b20-4686-9e90-95dfaeb8304d.png)

But I can't get it to work anymore and modifiers should automatically get merger according to this:
https://popper.js.org/docs/v2/faq/#how-do-i-set-modifier-defaults-and-allow-them-to-be-overridden

If you changed modifiers to be like in the second photo and it didn't help, then probably that is not the cause.

**Comment by mayank99** [comment]
@SStalciuss So from what I understand, changing the modifiers in `Popover.tsx#87` in your node modules like this did not help?

```diff
-        { name: 'preventOverflow', options: { padding: 0 } },
+        { name: 'preventOverflow', options: { padding: 0, rootBoundary: 'document' } },
```

Maybe you can tell us a bit about your real world scenario then? We might be able to come up with a different solution.

**Comment by SStalciuss** [comment]
Sadly, it didn't.

My problem is the same that I reproduced in here https://stackblitz.com/edit/react-ts-pmjwpw. I have a right panel that has a button inside of it. That button opens a modal that has fixed position, so it is always visible until it is closed. That modal has a combobox. But if combobox is not behind the right panel, the content is hidden.

**Comment by mayank99** [comment]
I think this might be because your modal is a child of the right panel. You could try using a [portal](https://reactjs.org/docs/react-dom.html#createportal). If you use the iTwinUI [`Modal`](https://itwin.github.io/iTwinUI-react/?path=/story/core-modal--basic), this will be automatically handled for you.

Does that fix it?

**Comment by mayank99** [comment]
It's true that these workarounds shouldn't be required but that's the reality right now. Is there any reason you don't want to use a portal? It was designed specifically for these cases. Also, in https://github.com/iTwin/iTwinUI-react/issues/783 we were investigating providing a way to disable _all_ hiding, but no luck.  Worst case, you could override our css to unhide it, but that's a worse workaround than using portals imo.

Apart from that, there isn't much we can do here as we rely on tippyjs and popper, both of which have unresolved bugs and have stopped shipping updates. In our next major version, we plan to migrate from tippyjs to floating-ui, hopefully that will fix it. We'll likely change the API to be more modular too, allowing toggling every plugin if possible.
