### ISSUE TITLE
Disable browser suggestion for ComboBox element 

### ISSUE THREAD

**Issue by neetra** [iTwin/iTwinUI-react#950]
#### Describe the bug (actual behavior)
Shows suggestions from browser as well as comboBox options.
#### Expected behavior
Disable auto- suggestion from the browser for ComboBox element.

#### Reproduction
click on the dropdown, you can see suggestions from drop-down

#### Problem:
•	The ComboBox, does not allow to add autocomplete = off property
•	Work around : Add property to <form>  adds property to all  child elements. However, we only want to disable for ComboBox (drop-down element).

**Comment by mayank99** [comment]
Thanks for the issue @neetra. I think some information is missing in your issue description or just jumbled up. Can you double check? A code sample or a link to a sandbox would help.

If you're trying to pass dom attributes to the native `<input>` element inside the combobox, then you need to do it through `inputProps`.

```jsx
<ComboBox
  options={options}
  inputProps={{ autocomplete: 'off' }}
/>
```

**Comment by neetra** [comment]
Thanks . It works .
However, I was unable find it in
1.  [core-combobox--basic](https://itwin.github.io/iTwinUI-react/?path=/docs/core-combobox--basic) document
2.  Not even 
![image](https://user-images.githubusercontent.com/30404609/204688095-c37c6cf1-86ae-4c31-b409-03ebb8cdde07.png)
