### ISSUE TITLE
ComboBox: broken layout when using virtualization

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI-react#984]
In v2, combobox with `enableVirtualization` looks broken. The menu takes up all the available height and doesn't scroll properly.
![](https://user-images.githubusercontent.com/9084735/206721353-11806f78-ffd5-4a59-875b-bfc23d24b657.png)

https://itwin.github.io/iTwinUI-react/?path=/story/core-combobox--virtualized
https://itwin.github.io/iTwinUI-react/iframe.html?args=&id=core-combobox--virtualized&viewMode=story

**Comment by bentleyvk** [comment]
How visual tests then passed?

**Comment by mayank99** [comment]
apparently we don't test the virtualized combobox 😆 

https://github.com/iTwin/iTwinUI-react/blob/21900d42900f7a03305bf2040cc64ddb29361b2d/apps/storybook/src/ComboBox.test.ts#L7-L16

**Comment by mayank99** [comment]
Fixed in #986, released in `@itwin/itwinui-react`@**`2.0.3`** 🎉
